/** Standalone recovery UI: no application bundle, plugins, remote assets or error HTML. */
export const recoveryPanelHtml = `<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'"><title>插件恢复 · AgentWorkbench</title><style>
:root{color-scheme:light dark;font:15px/1.55 system-ui,sans-serif;color:#302e2b;background:#faf9f6}*{box-sizing:border-box}body{margin:0;padding:30px;max-width:900px}h1{font-size:24px;margin:0 0 10px}h2{font-size:16px;margin:0 0 6px}p{margin:8px 0}.muted{color:#746f67}.status{padding:12px 0;border-bottom:1px solid #d8d3ca}.incident{padding:15px 0;border-bottom:1px solid #d8d3ca}code{font-size:12px;overflow-wrap:anywhere}.actions,.copy-actions{display:flex;gap:8px;flex-wrap:wrap}.actions{margin-top:20px}.copy-actions{width:100%}button{font:inherit;padding:8px 14px;border:1px solid #b8b1a7;border-radius:7px;color:inherit;background:transparent;cursor:pointer}button.primary{background:#675444;color:white;border-color:#675444}button:disabled{opacity:.5;cursor:default}button:focus-visible{outline:2px solid #88715e;outline-offset:3px}#notice{white-space:pre-wrap}#issues{max-height:48vh;overflow:auto}small{display:block}.badge{font-size:12px;border:1px solid #b8b1a7;border-radius:4px;padding:1px 5px;margin-left:8px}@media(prefers-color-scheme:dark){:root{color:#eee9e4;background:#242424}.muted{color:#b6afa7}.status,.incident{border-color:#49453f}button{border-color:#777067}}@media(max-width:520px){body{padding:20px}.actions button{width:100%}}
</style></head><body><h1>工作台插件恢复</h1><p id="summary" role="status">正在读取启动诊断…</p><p class="muted">安全模式暂停第三方工作台插件，保留配置和启用偏好。内置功能与原生运行时的官方插件不受影响。</p><div class="status" id="versions"></div><div id="issues" aria-label="插件诊断"></div><p id="notice" role="alert"></p><div class="actions"><button id="repair">一键修复兼容问题</button><button class="primary" id="safe">以安全模式重启</button><button id="continue">继续使用工作台</button><button id="normal">退出安全模式并重启</button><div class="copy-actions"><button id="copy">复制诊断信息</button><button id="copy-repair">复制诊断并准备 Agent 修复草稿</button><button id="quit">退出</button></div></div><p class="muted"><small>批量修复会逐个应用已登记的旧接口适配，单项失败不阻断其余插件；未执行的插件仍属未检查。自动修复不修改插件代码、不提升接口版本或重新批准变更包。无法修复时，可复制修复草稿并进入安全模式。草稿会填入新会话文本框，不会自动发送或选择模型。</small></p><script>
const $=id=>document.getElementById(id);let current,busy=null;
const labels={PLUGIN_API_VERSION_UNSUPPORTED:'插件声明的 API 版本不受支持',HOST_VERSION_UNSUPPORTED:'工作台版本超出插件声明的支持范围',SERVICE_UNAVAILABLE:'插件依赖的服务当前不可用',SERVICE_CONTRACT_UNSUPPORTED:'服务接口版本发生变化',SERVICE_MEMBER_UNAVAILABLE:'插件依赖的接口成员已不可用',PLUGIN_HOST_ACTIVATION_FAILED:'插件宿主代码加载失败',PLUGIN_RENDERER_ACTIVATION_FAILED:'插件界面代码执行失败',PLUGIN_ACTIVATION_TIMEOUT:'插件激活超时，已停止等待',PLUGIN_CLEANUP_FAILED:'插件清理失败或超时',PLUGIN_PACKAGE_INVALID:'插件文件或清单无法读取',PLUGIN_PREFERENCES_INVALID:'插件偏好文件损坏，已保留原文件',PLUGIN_DIRECTORY_UNAVAILABLE:'插件目录无法读取',PLUGIN_STARTUP_INTERRUPTED:'上次加载未完成，已阻止自动重试',PLUGIN_RECOVERY_STATE_INVALID:'恢复记录损坏，已进入安全模式',PLUGIN_PROCESS_UNRESPONSIVE:'工作台主进程长时间未响应',PLUGIN_RENDERER_UNRESPONSIVE:'工作台界面长时间未响应',PLUGIN_PROCESS_EXITED:'工作台进程意外退出',PLUGIN_RENDERER_CRASHED:'工作台界面进程退出',WORKBENCH_STARTUP_INCOMPLETE:'核心启动未完成，可能有插件阻塞接口',PLUGIN_GUARDIAN_UNAVAILABLE:'独立恢复进程不可用，已暂停第三方插件',WORKBENCH_RENDER_FAILED:'核心界面加载失败，尚不能确认与插件有关'};
function render(v){current=v;const s=v.snapshot;$('summary').textContent=v.hung?'工作台未响应，可从此独立窗口进入安全模式。':v.disconnected?'工作台已退出。诊断仅记录已观察到的加载阶段。':s.safeMode?'当前处于安全模式，第三方工作台插件已暂停。':s.incidents.length?'检测到插件加载或兼容问题。':'未检测到插件启动故障。';$('versions').textContent='当前工作台 '+s.hostVersion+(s.previousHostVersion&&s.previousHostVersion!==s.hostVersion?' · 上次 '+s.previousHostVersion:'');$('issues').replaceChildren();for(const i of [...s.incidents].reverse()){const row=document.createElement('section');row.className='incident';const title=document.createElement('h2');title.textContent=i.name||i.id;const badge=document.createElement('span');badge.className='badge';badge.textContent=i.certainty==='confirmed'?'已定位':i.certainty==='suspected'?'疑似相关':'归因未知';title.append(badge);const text=document.createElement('p');text.textContent=labels[i.code]||'插件故障';const meta=document.createElement('code');meta.textContent=i.id+' · '+i.phase+' · '+i.code+(i.version?' · 插件 '+i.version:'')+(i.issues?.length?' · '+i.issues.map(issue=>[issue.service,issue.member,issue.expected===undefined?'':'所需 v'+issue.expected,issue.actual===undefined?'':'当前 v'+issue.actual].filter(Boolean).join(' / ')).join('; '):'');const help=document.createElement('small');help.className='muted';help.textContent=i.repairable?'已提供对应的旧接口适配，可尝试一键修复。':'没有可验证的自动修复方案；请先用安全模式进入，再检查插件。';row.append(title,text,meta,help);$('issues').append(row);}const available=!v.hung&&!v.disconnected;$('repair').disabled=busy||!available||s.safeMode||!s.incidents.some(i=>i.repairable);$('safe').disabled=!!busy&&busy!=='repair';$('normal').hidden=!s.safeMode;$('normal').disabled=busy;$('continue').disabled=busy||!available||s.boot!=='ready';$('copy').disabled=busy;$('copy-repair').disabled=busy;}
async function act(action){if(busy&&!(busy==='repair'&&['safe','quit'].includes(action)))return;busy=action;render(current);if(action==='repair')$('notice').textContent='正在逐项应用兼容适配；单个失败后继续检查其余插件。如工作台失去响应，仍可进入安全模式。';try{const result=await window.workbench.call('recovery/'+action);$('notice').textContent=result?.message||'';}catch{$('notice').textContent='操作未确认。请保留此窗口，尝试安全模式；不要反复重试插件。';}finally{if(busy===action)busy=null;await refresh();}}
async function refresh(){try{render(await window.workbench.call('recovery/status'));}catch{}}
for(const id of ['repair','safe','continue','normal','copy','copy-repair','quit'])$(id).onclick=()=>act(id);refresh();setInterval(refresh,1000);
</script></body></html>`;
