import path from 'node:path';
import type { NativeHomes, Provider } from './sources';

/** Receiving-side reference contract; this does not impersonate native automatic ingestion. */
export function receiverReferenceGuide(runtime:Provider,homes:NativeHomes):string {
  return runtime==='codex'
    ? `Receiving runtime: Codex. Follow the Codex instructions loaded by this native session. Inspect this recipient's existing memory and effective AGENTS.override.md/AGENTS.md before deciding what is durable. Codex generated MEMORY.md and memory_summary.md remain runtime-owned. The host tool can store a scoped, indexed reference under ${JSON.stringify(path.join(homes.codex,'memories','received'))}; it cannot run Codex's official automatic consolidation. Do not impose Claude auto-memory metadata or write into the Claude store. If a necessary policy is unknown or conflicts, leave that archive pending and explain the blocker.`
    : `Receiving runtime: Claude Code. Follow the Claude Code instructions loaded by this native session and inspect this recipient's effective CLAUDE.md and existing project memory before deciding what is durable. Keep project scope and any user/feedback/project/reference distinctions in the summary. Native auto MEMORY.md is a short startup index; do not copy a Codex generated registry wholesale or rewrite Claude's native generated index. The host tool stores scoped, indexed references under ${JSON.stringify(path.join(homes.claude,'memory','received'))}. It cannot run Claude's official automatic memory mechanism. Do not write into the Codex store. If a necessary policy is unknown or conflicts, leave that archive pending and explain the blocker.`;
}

/** Selected by frozen runtime identity, never provider/model labels. */
export function formatGuide(runtime: Provider, homes: NativeHomes): string {
  if (runtime === 'claude') return `Native Claude Code format: inspect installed memory instructions and effective settings. Global instructions use ${JSON.stringify(path.join(homes.claude, 'CLAUDE.md'))}; auto memory normally uses ${JSON.stringify(path.join(homes.claude, 'projects', '<native-project-key>', 'memory'))} or effective autoMemoryDirectory. Discover the actual project key; never guess it. Use a short MEMORY.md index linking topic .md files, within the first 200 lines and 25,000 bytes. Follow installed topic metadata conventions, including name, description and type (user/feedback/project/reference) where required. Global instructions stay global; project facts stay scoped. Verify auto memory is enabled and the index belongs to the effective store. If this cannot be established, leave pending.`;
  return `Native Codex format: inspect this installation's memory-writing instructions and enabled native memory capability. Generated memory normally lives under ${JSON.stringify(path.join(homes.codex, 'memories'))}, with memory_summary.md, MEMORY.md and runtime-owned supporting files. Global instructions use the effective AGENTS.override.md or AGENTS.md under ${JSON.stringify(homes.codex)}. Do not impose Claude's format. Use only an actually supported native ingestion route; never blindly overwrite generated indexes or invent an API. A queued ad-hoc note alone is not a completed import: require actual indexed native storage before returning a receipt. If there is no safe supported route, leave pending and explain briefly. Standalone native use must not depend on the depot.`;
}
