import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { EventEmitter } from 'node:events';
import { StateStore, SecretStore, initialState } from '../apps/desktop/host/store';
import { WorkbenchController } from '../apps/desktop/host/controller';
import { NativeResources } from '../apps/desktop/host/native-resources';
import { attachNativeObservation } from '../apps/desktop/host/native-observation';
import { SharedMemoryStore } from '../packages/memory-core';
import { SharedSkillsStore } from '../packages/skills-core';
import { HostServiceRegistry } from '../packages/plugins-core/services';
import { officialModelGroups,chooseOfficialModel,officialAccountTarget } from '../packages/model-management/selection';
import { localAccountRef, type LocalModelAccount } from '../packages/model-management/types';
import type { ModelTarget } from '../packages/model-api/types';
import type { Session } from '../packages/contracts';

const ids=['11111111-1111-4111-a111-111111111111','22222222-2222-4222-a222-222222222222','33333333-3333-4333-a333-333333333333'];
const accounts:LocalModelAccount[]=ids.map((id,i)=>({id,revision:'r',provider:i===2?'claude':'codex',enabled:true,name:'Account '+i,status:'authenticated',models:[{id:'model',model:i===2?'sonnet':'gpt-model',name:i===2?'Sonnet':'GPT model',isDefault:true,efforts:['low','high'],defaultEffort:'low',serviceTiers:[]}]}));
async function fixture(){const directory=await mkdtemp(path.join(os.tmpdir(),'awb-account-selection-')),store=new StateStore(directory);await store.load();await store.update(s=>{s.localModelAccounts=structuredClone(accounts);});const native=new NativeResources(directory,{openZip:async()=>null,saveZip:async()=>null},()=>[],()=>{},directory,{cliOptions:{executables:{codex:process.execPath,claude:process.execPath}}});const controller=new WorkbenchController(store,new SecretStore(directory,{encrypt:()=>{throw Error('No credentials');},decrypt:()=>{throw Error('No credentials');}}),{pickDirectory:async()=>null,copy:()=>{},openPath:async()=>{},nativeCapabilities:()=>[]},()=>{},{memory:new SharedMemoryStore(directory),skills:new SharedSkillsStore(directory),native});return{store,controller,directory,close:async()=>{await controller.dispose();await rm(directory,{recursive:true,force:true});}};}
test('official model groups stay runtime-specific, deduplicate accounts and never include API aliases',async()=>{const f=await fixture();try{const targets=await f.controller.call('model-targets/list') as ModelTarget[];const api={...targets[0]!,id:'api/source/model/codex',binding:{...targets[0]!.binding,localAccountId:undefined,modelConnectionId:'api'}};const groups=officialModelGroups([...targets,api],'codex');assert.equal(groups.length,1);assert.equal(groups[0]!.accounts.length,2);assert.equal(officialModelGroups(targets,'claude')[0]!.model,'sonnet');assert.equal(chooseOfficialModel(groups[0]!.accounts,ids[1])?.binding.localAccountId,ids[1]);assert.throws(()=>officialAccountTarget(targets,'codex','gpt-model',ids[2]!),/UNAVAILABLE/);}finally{await f.close();}});
test('official account, model, effort and project runtime permission survive restart without fallback',async()=>{const f=await fixture();try{const targets=await f.controller.call('model-targets/list') as ModelTarget[],target=targets.find(t=>t.binding.localAccountId===ids[1])!,selection={model:'gpt-model',effort:'high'};await f.controller.call('runtime/select',{runtime:'codex',targetId:target.id,selection});await f.controller.call('permissions/remember',{projectId:null,runtime:'codex',permissionMode:'full-access'});let loaded=await new StateStore(f.directory).load();assert.equal(loaded.lastModelTargetId,target.id);assert.deepEqual(loaded.lastModelSelection,selection);const session=await f.controller.call('session/create',{modelTargetId:target.id,modelSelection:selection}) as Session;assert.equal(session.permissionMode,'full-access');assert.equal(session.binding.hostId,undefined);assert.equal(session.binding.modelConnectionId,undefined);assert.equal(session.binding.localAccountId,ids[1]);await assert.rejects(f.controller.call('runtime/select',{runtime:'claude',targetId:target.id,selection}));await f.controller.call('models/accounts/set-enabled',{id:ids[1],revision:'r',enabled:false});loaded=await new StateStore(f.directory).load();assert.equal(loaded.lastModelTargetId,target.id);await assert.rejects(f.controller.call('session/create',{modelTargetId:target.id,modelSelection:selection}));assert.equal(loaded.sessions.length,1);}finally{await f.close();}});
test('switching accounts retains model and effort with an independent native thread binding',async()=>{const f=await fixture();try{const targets=await f.controller.call('model-targets/list') as ModelTarget[],a=targets[0]!,b=targets[1]!;const s=await f.controller.call('session/create',{modelTargetId:a.id,modelSelection:{model:'gpt-model',effort:'high'}}) as Session;await f.store.update(state=>{state.sessions[0]!.binding.nativeSessionId='first-native-thread';});await f.controller.call('session/model-target',{sessionId:s.id,targetId:b.id,selection:{model:'gpt-model',effort:'high'}});const next=f.store.snapshot().sessions[0]!;assert.equal(next.binding.localAccountId,ids[1]);assert.equal(next.binding.nativeSessionId,undefined);assert.equal(next.modelSelection?.effort,'high');assert.equal(next.modelLanes?.[0]?.binding.nativeSessionId,'first-native-thread');assert.throws(()=>f.controller.localAccounts.execution({...next,binding:{...next.binding,modelConnectionId:'injected-api'}}),/UNAVAILABLE/);}finally{await f.close();}});
test('local official observation persists root token receipts once and ignores child totals',async()=>{const f=await fixture();try{const target=(await f.controller.call('model-targets/list') as ModelTarget[])[0]!;const s=await f.controller.call('session/create',{modelTargetId:target.id}) as Session;await f.store.update(state=>{state.sessions[0]!.binding.nativeSessionId='native';});const source=new EventEmitter(),observation=attachNativeObservation(s.id,source,()=>f.store.snapshot(),fn=>f.store.update(fn));const emit=(threadId:string)=>source.emit('event',{sessionId:s.id,public:false,raw:{receivedAt:new Date().toISOString(),value:{method:'thread/tokenUsage/updated',params:{threadId,turnId:'turn',tokenUsage:{total:{inputTokens:100,outputTokens:10,cachedInputTokens:50,totalTokens:110},last:{inputTokens:100,outputTokens:10,cachedInputTokens:50,totalTokens:110}}}}}});emit('native');emit('native');emit('child');await observation.flush();assert.equal(f.store.snapshot().modelUsage?.length,1);assert.equal(f.store.snapshot().modelUsage?.[0]?.scope.id,ids[0]);assert.equal(f.store.snapshot().modelUsage?.[0]?.totalTokens,110);await observation.dispose();}finally{await f.close();}});
test('public model service interception reaches host calls and removal restores the implementation',async()=>{const f=await fixture();try{const services=new HostServiceRegistry();services.register('models.accounts',f.controller.localAccounts);let calls=0;const undo=services.intercept('models.accounts','call',(next,...args)=>{calls++;return next(...args);});await f.controller.call('models/accounts/list');assert.equal(calls,1);undo();await f.controller.call('models/accounts/list');assert.equal(calls,1);}finally{await f.close();}});
