import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {setTimeout as wait} from 'node:timers/promises';import {ModelConnections} from '../apps/desktop/host/model-connections';import {StateStore,SecretStore} from '../apps/desktop/host/store';import type {ModelConnection} from '../packages/model-api/types';import {ReasoningJobs} from '../apps/desktop/host/reasoning-jobs';import {validateConnection} from '../packages/model-api/config';
const config=()=>({name:'Fixture',baseUrl:'https://example.invalid/v1',protocol:'responses',models:[{id:'m',model:'model',name:'Model',enabled:true}]});
const response=(request:RequestInit|undefined)=>{const b=JSON.parse(String(request?.body)),effort=b.reasoning?.effort;return !effort||['low','medium','xhigh'].includes(effort)?Response.json({status:'completed',output:[]}):Response.json({error:{param:'reasoning.effort',message:'Unsupported effort'}},{status:400});};
async function until(check:()=>boolean|Promise<boolean>){for(let i=0;i<100;i++){if(await check())return;await wait(30);}throw Error('fixture timed out');}
async function fixture(fetcher:typeof fetch,busy=()=>false){const dir=await mkdtemp(path.join(os.tmpdir(),'awb-bg-')),store=new StateStore(dir);await store.load();const secrets=new SecretStore(path.join(dir,'secrets'),{encrypt:s=>Buffer.from(s),decrypt:b=>b.toString()});const connections=new ModelConnections({snapshot:()=>store.snapshot(),update:change=>store.update(change),busy},secrets,fetcher);return {connections,store,close:async()=>{connections.dispose();await rm(dir,{recursive:true,force:true});}};}
test('background save returns during a blocked probe, skips directory requests, and publishes verified defaults later',async()=>{let release!:()=>void;const blocked=new Promise<void>(r=>release=r);let calls=0;const f=await fixture(async(_url,init)=>{assert.equal(init?.method,'POST');calls++;if(calls===1)await blocked;return response(init);});try{const saved=await Promise.race([f.connections.call('model-api/save',{connection:config(),backgroundReasoning:true,allowInference:true}),wait(700).then(()=>{throw Error('save waited for probe');})]) as ModelConnection;assert.equal(f.store.snapshot().modelConnections?.length,1);assert.equal(saved.models[0]!.reasoningProbe,undefined);release();await until(()=>!!f.connections.connection(saved.id).models[0]!.reasoningProbe);const actual=f.connections.connection(saved.id);assert.deepEqual(actual.models[0]!.efforts,['low','medium','xhigh']);assert.equal(actual.models[0]!.defaultEffort,'medium');assert.equal(actual.revision,saved.revision);assert.equal(calls,7);}finally{release();await f.close();}});
test('draft detection is independent of busy settings; harmless additions save, endpoint changes remain blocked',async()=>{let busy=false;const f=await fixture(async(_u,i)=>response(i),()=>busy);try{let saved=await f.connections.call('model-api/save',{connection:config(),backgroundReasoning:true,allowInference:true}) as ModelConnection;await until(()=>!!f.connections.connection(saved.id).models[0]!.reasoningProbe);saved=f.connections.connection(saved.id);busy=true;const job=await f.connections.call('model-api/reasoning/start',{allowInference:true,id:saved.id,connection:{...saved,models:[...saved.models,{id:'other',model:'other',name:'Other',enabled:true}]}}) as {id:string};assert.ok(job.id);const changed={...saved,name:'Renamed',models:[...saved.models,{id:'other',model:'other',name:'Other',enabled:true}]};const next=await f.connections.call('model-api/save',{id:saved.id,revision:saved.revision,connection:changed,backgroundReasoning:true,allowInference:true,jobId:job.id}) as ModelConnection;assert.equal(next.models.length,2);await assert.rejects(f.connections.call('model-api/save',{id:next.id,revision:next.revision,connection:{...next,baseUrl:'https://other.invalid/v1'},backgroundReasoning:true,allowInference:true}),/正在使用/);busy=false;await until(()=>!!f.connections.connection(next.id).models[1]!.reasoningProbe);}finally{await f.close();}});
test('cancelled jobs cannot overwrite newer configurations and public status contains no key',async()=>{let release!:()=>void;const blocked=new Promise<void>(r=>release=r);const jobs=new ReasoningJobs(async(_url,init)=>{await blocked;return response(init);});try{const c=validateConnection(config()),job=jobs.start(c,'fixture-secret');assert.doesNotMatch(JSON.stringify(job),/fixture-secret|baseUrl|fingerprint/);jobs.cancel(job.id);release();await until(()=>jobs.status(job.id).state==='cancelled');assert.equal(jobs.status(job.id).models.length,0);assert.equal(jobs.attach(job.id,c,'fixture-secret',async()=>{throw Error('cancelled job applied');}),false);}finally{release();jobs.dispose();}});

test('completed in-memory jobs expire after the evidence cache window',async()=>{let now=Date.now();const jobs=new ReasoningJobs(async(_u,i)=>response(i),()=>now);try{const c=validateConnection(config()),first=jobs.start(c,'');await until(()=>jobs.status(first.id).state==='complete');assert.equal(jobs.start(c,'').id,first.id);now+=86400001;assert.equal(jobs.attach(first.id,c,'',async()=>{}),false);assert.notEqual(jobs.start(c,'').id,first.id);}finally{jobs.dispose();}});

test('a full background queue never turns a persisted save into an apparent failure',async()=>{const f=await fixture(async(_u,i)=>new Promise((_resolve,reject)=>i?.signal?.addEventListener('abort',()=>reject(Error('cancelled')),{once:true})));try{for(let n=0;n<4;n++)await f.connections.call('model-api/reasoning/start',{allowInference:true,connection:{...config(),baseUrl:`https://queue${n}.invalid/v1`}});const saved=await f.connections.call('model-api/save',{connection:config(),backgroundReasoning:true,allowInference:true}) as ModelConnection & {reasoningJobError?:string};assert.equal(saved.reasoningJobError,'REASONING_DETECTION_UNAVAILABLE');assert.equal(f.store.snapshot().modelConnections?.[0]?.id,saved.id);await assert.rejects(f.connections.call('model-api/save',{connection:config(),backgroundReasoning:true,verifyReasoning:true,allowInference:true}),/MODE_INVALID/);}finally{await f.close();}});
