import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp,readFile,writeFile,rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { StateStore,SecretStore,initialState } from '../apps/desktop/host/store';
import { translationProfile } from '../apps/desktop/host/validation';
test('serialized state updates preserve concurrent changes and restart',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'aw-store-'));try{const store=new StateStore(dir);await store.load();await Promise.all([store.update(s=>{s.theme='dark';}),store.update(s=>{s.translateProgress=true;})]);const reload=new StateStore(dir);const state=await reload.load();assert.equal(state.theme,'dark');assert.equal(state.translateProgress,true);}finally{await rm(dir,{recursive:true});}});
test('secret is origin/config bound and crypto failure never falls back to plaintext',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'aw-secret-'));try{const encrypted=Buffer.from('not-a-real-credential');const vault=new SecretStore(dir,{encrypt:()=>encrypted,decrypt:()=>JSON.stringify({scope:'https://a.example/v1',key:'synthetic'})});await vault.set('https://a.example/v1','synthetic');assert.equal(await vault.get('https://b.example/v1'),'');assert.equal(await vault.get('https://a.example/v1'),'synthetic');assert.ok(!(await readFile(path.join(dir,'translation-key.bin'),'utf8')).includes('synthetic'));const broken=new SecretStore(dir,{encrypt:()=>{throw new Error('unavailable');},decrypt:()=>''});await assert.rejects(broken.set('a','secret'));}finally{await rm(dir,{recursive:true});}});
test('renderer cannot self-assert verified model effort',()=>{assert.throws(()=>translationProfile({name:'x',baseUrl:'https://a.example/v1',protocol:'responses',model:'m',consent:true,effort:'ultra',verifiedEfforts:['ultra'],maxCharacters:1000,maxCalls:10,timeoutMs:10000}),/尚未实测/);});
test('only the exact legacy empty welcome container migrates; history and real projects remain',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'aw-migrate-'));try{
 const saved=initialState();saved.projects=[{id:'welcome',name:'开始使用',path:'',authority:'local',group:''},{id:'real',name:'开始使用',path:dir,paths:[dir],authority:'local',group:''}];
 saved.sessions=[{id:'legacy',projectId:'welcome',projectPath:'',title:'Keep my thread',pinned:true,archived:false,group:'',binding:{runtime:'demo',provider:'offline',accountRef:'none',executionId:'local',egress:'demo'},status:'idle',messages:[{id:'message',role:'user',original:'Keep this exact text',demo:true,timestamp:'fixture'}],createdAt:'fixture'}];
 await writeFile(path.join(dir,'state.json'),JSON.stringify(saved));const store=new StateStore(dir);const migrated=await store.load();assert.equal(migrated.projects.length,1);assert.equal(migrated.projects[0]?.id,'real');assert.equal(migrated.sessions[0]?.projectId,null);assert.deepEqual(migrated.sessions[0]?.messages,saved.sessions[0]?.messages);assert.equal(migrated.sessions[0]?.pinned,true);
 const changed={...saved,projects:[{...saved.projects[0]!,name:'My custom project'}]};await writeFile(path.join(dir,'state.json'),JSON.stringify(changed));const preserved=await new StateStore(dir).load();assert.equal(preserved.projects[0]?.id,'welcome');assert.equal(preserved.sessions[0]?.projectId,'welcome');
}finally{await rm(dir,{recursive:true});}});
