import test from 'node:test';
import assert from 'node:assert/strict';
import { protect,restore,hashText,assertNoSecrets } from '../packages/translation/protection';
import { Translator,listModels,endpoint,protocolCandidates } from '../packages/translation/provider';
import { InputGate } from '../packages/translation/gate';
import { OverlayStore } from '../packages/translation/overlay';
import { TranslationQueue } from '../packages/translation/queue';
import { TranslationPolicyGate } from '../packages/translation/policy';
import type { NativeEvent, TranslationProfile, TranslationResult } from '../packages/contracts/index';
const base:TranslationProfile={id:'p',name:'test',baseUrl:'https://translate.example/v1',protocol:'chat-completions',model:'fixture-model',verifiedEfforts:[],consent:true,maxCharacters:10000,maxCalls:20,timeoutMs:10000};
const result=(source:string):TranslationResult=>({text:'中文',sourceHash:hashText(source),providerId:'p',model:'fixture',direction:'output',elapsedMs:1,inputTokens:null,outputTokens:null,requestedEffort:null,effectiveEffort:null,protectionVersion:1});
const deferred=<T>()=>{let resolve!:(v:T)=>void;const promise=new Promise<T>(r=>{resolve=r;});return {promise,resolve};};
test('protected code, mixed paths, URL, quoted literal, hashes round-trip byte exactly',()=>{
 const input='检查 `src/main.ts`，不要修改。\r\n```ts\nconst 汉字 = "原样";\n```\n"D:\\目录 空格\\模型.blend"\n\\\\server\\share\\文件.txt\n/home/owner/project/a.py\nhttps://example.test/a?q=中&n=1\n“保留这句话”\n'+ 'a'.repeat(64);
 const p=protect(input);assert.equal(restore(p.text,p),input);assert.ok(p.spans.length>=7);assert.ok(!p.text.includes('const 汉字'));assert.ok(!p.text.includes('模型.blend'));assert.ok(!p.text.includes('example.test'));
});
test('standalone JSON and diff are exact protected payloads',()=>{for(const input of ['{ "name": "中文", "count": 2 }','diff --git a/a b/a\n--- a/a\n+++ b/a\n@@ -1 +1 @@\n-旧\n+新']){const p=protect(input);assert.equal(p.spans.length,1);assert.equal(restore(p.text,p),input);}});
test('command lines remain literal and incomplete code blocks fail closed',()=>{const source='请运行：\nnpm test -- --file 中文.txt\n不要修改文件';const p=protect(source);assert.ok(p.spans.some(s=>s.original.includes('npm test')));assert.equal(restore(p.text,p),source);assert.throws(()=>protect('```js\nconst token = 1;'),/围栏/);});
test('nested code protection preserves quote and list prefixes without freezing nearby prose',()=>{
 for(const input of ['- Description\n\n  ```js\n  const text = "literal";\n  ```\n\n  Continue.','- Description\n\n      const text = "literal";\n\n  Continue.','> Description\n>\n> ```js\n> const text = "literal";\n> ```\n>\n> Continue.','Description\r\n\r\n- ```js\r\n  const text = "literal";\r\n  ```\r\n\r\nContinue.','Description\n\n````md\n```js\nliteral\n```\n````\n\nContinue.']){const value=protect(input);assert.equal(restore(value.text,value),input);assert.ok(!value.text.includes('literal'));assert.ok(value.text.includes('Description'));assert.ok(value.text.includes('Continue.'));}
 for(const input of ['- Description\n\n  ```js\n  const text = "literal";','```'])assert.throws(()=>protect(input),/围栏/);
});
test('missing duplicated modified or foreign placeholder is rejected',()=>{const p=protect('修改 `x.ts`');const token=p.spans[0]!.token;assert.throws(()=>restore('changed',p));assert.throws(()=>restore(token+token,p));assert.throws(()=>restore(token.replace('AW_','AX_'),p));assert.throws(()=>restore(token+'⟦AW_bad_0⟧',p));});
test('credential-looking input is stopped before third party',()=>{assert.throws(()=>assertNoSecrets('api_key=abcdefghijklmnop'));assert.throws(()=>protect('-----BEGIN OPENSSH PRIVATE KEY-----'));});
test('endpoint rejects secrets, nonlocal plaintext URL and queries',()=>{for(const url of ['http://a.example','https://user:pass@a.example','https://a.example?x=1','http://192.168.1.2/v1'])assert.throws(()=>endpoint(url,'models'));assert.equal(endpoint('https://api.example/v1/','models').href,'https://api.example/v1/models');assert.equal(protocolCandidates('https://unknown.example/v1').length,3);});
for(const protocol of ['chat-completions','responses','anthropic-messages'] as const)test(`real request shaping and extraction: ${protocol}`,async()=>{
 let calls=0;
 const translator=new Translator(async(url,init)=>{calls++;assert.equal(init?.redirect,'error');assert.equal(init?.method,'POST');const body=JSON.parse(String(init?.body));assert.equal(body.model,'fixture-model');assert.ok(!JSON.stringify(body).includes('src/main.ts'));
  const text=protocol==='responses'?body.input:body.messages.at(-1).content;const answer=text.replace('请检查','Please inspect');
  if(protocol==='anthropic-messages')assert.equal((init?.headers as any)['x-api-key'],'fixture-key');else assert.equal((init?.headers as any).authorization,'Bearer fixture-key');
  const data=protocol==='responses'?{status:'completed',output:[{type:'message',content:[{type:'output_text',text:answer}]}],usage:{input_tokens:20,output_tokens:10}}:protocol==='anthropic-messages'?{stop_reason:'end_turn',content:[{type:'text',text:answer}],usage:{input_tokens:20,output_tokens:10}}:{choices:[{finish_reason:'stop',message:{content:answer}}],usage:{prompt_tokens:20,completion_tokens:10}};
  return Response.json(data);
 });
 const value=await translator.translate('请检查 `src/main.ts`','input',{...base,protocol},'fixture-key');assert.equal(value.text,'Please inspect `src/main.ts`');assert.equal(value.inputTokens,20);assert.equal(value.effectiveEffort,null);assert.equal(calls,1);
});
test('truncation is not accepted as completed translation',async()=>{const t=new Translator(async()=>Response.json({choices:[{finish_reason:'length',message:{content:'partial'}}]}));await assert.rejects(t.translate('测试','input',base,'fixture'));});
test('HTTP error does not echo upstream sensitive body or retry automatically',async()=>{let n=0;const t=new Translator(async()=>{n++;return new Response('Bearer SECRET',{status:429});});await assert.rejects(t.translate('测试','input',base,'fixture'),/HTTP 429/);assert.equal(n,1);});
test('malformed upstream JSON never leaks a reflected credential in parser errors',async()=>{const reflected='qwerty-FIXTURE-CREDENTIAL-0987654321';const t=new Translator(async()=>new Response(reflected));await assert.rejects(t.translate('测试','input',base,'fixture'),error=>error instanceof Error&&error.message.includes('合法 JSON')&&!error.message.includes(reflected));});
test('revoking consent cancels queued work before it can send',async()=>{const queue=new TranslationQueue(1);const policy=new TranslationPolicyGate();const blocking=deferred<void>();const a=queue.enqueue('a','input',()=>blocking.promise);const token=policy.capture();let sent=0;const pending=queue.enqueue('b','final',async()=>{policy.assert(token);sent++;},token.signal);const denied=assert.rejects(pending);policy.invalidate();blocking.resolve();await Promise.all([a,denied]);assert.equal(sent,0);});
test('configuration transactions block new admissions until every concurrent save completes',()=>{const gate=new TranslationPolicyGate();const before=gate.capture();const finishA=gate.beginConfigurationChange();const finishB=gate.beginConfigurationChange();assert.throws(()=>gate.capture(),/正在保存/);assert.throws(()=>gate.assert(before));finishA();assert.throws(()=>gate.capture());finishA();assert.throws(()=>gate.capture());finishB();assert.doesNotThrow(()=>gate.capture());});
test('preview helper integrates a supplement then translates the full revised request',async()=>{let calls=0;const t=new Translator(async(_url,init)=>{calls++;const body=JSON.parse(String(init?.body));const input=body.messages[1].content as string;const token=input.match(/⟦AW_[^⟧]*⟧/)?.[0];assert.ok(token);const edit=(body.messages[0].content as string).includes('prompt editing assistant');return Response.json({choices:[{finish_reason:'stop',message:{content:edit?`请检查 ${token}，不要修改文件，并说明风险。`:`Please inspect ${token}, do not modify files, and explain the risks.`}}]});});const revised=await t.integrateSupplement('请检查 `src/main.ts`，不要修改文件。','还需要说明风险。',base,'fixture');assert.equal(calls,2);assert.equal(revised.original,'请检查 `src/main.ts`，不要修改文件，并说明风险。');assert.match(revised.translated,/explain the risks/);assert.ok(revised.translated.includes('`src/main.ts`'));});
test('model refinement invalidates the old preview and publishes only the full new revision',async()=>{const gate=new InputGate();const id=gate.create('s','旧中文');const old=await gate.prepare(id,async()=>'Old English');const next=gate.beginRevision(id,'s',old.sourceHash);await assert.rejects(gate.submit(id,'s',old.sourceHash,async()=>{}));const updated=await gate.prepareRevision(next.id,old,'补充风险',async()=>({original:'新中文含风险',translated:'New English with risks'}));assert.equal(updated.revision,2);assert.equal(updated.revisions?.[0]?.source,'旧中文');let sent='';await gate.submit(next.id,'s',updated.sourceHash,async t=>{sent=t;});assert.equal(sent,'New English with risks');});
test('unsupported effort, consent, size, and budgets fail closed',async()=>{let n=0;const t=new Translator(async()=>{n++;return Response.json({choices:[{finish_reason:'stop',message:{content:'Test'}}]});});await assert.rejects(t.translate('测试','input',{...base,effort:'high'},'fixture'));await assert.rejects(t.translate('测试','input',{...base,consent:false},'fixture'));await assert.rejects(t.translate('测试','input',{...base,maxCharacters:1},'fixture'));assert.equal(n,0);await t.translate('测试','input',{...base,maxCalls:1},'fixture');await assert.rejects(t.translate('测试','input',{...base,maxCalls:1},'fixture'),/预算/);});
test('catalog GET carries correct auth and only returns actual IDs',async()=>{const models=await listModels(base,'fixture',async(url,init)=>{assert.equal(String(url),'https://translate.example/v1/models');assert.equal(init?.redirect,'error');assert.equal(init?.method,'GET');return Response.json({data:[{id:'a'},{id:'b'},{id:'a'},{}]});});assert.deepEqual(models,['a','b']);});
test('input revision discards late translation without dispatching',async()=>{const gate=new InputGate();const old=gate.create('s','旧');const wait=deferred<string>();const pending=gate.prepare(old,()=>wait.promise);gate.create('s','新');wait.resolve('old');await assert.rejects(pending);});
test('explicit cancel blocks late completion',async()=>{const gate=new InputGate();const id=gate.create('s','中');const wait=deferred<string>();const pending=gate.prepare(id,()=>wait.promise);gate.cancel(id);wait.resolve('English');await assert.rejects(pending);assert.equal(gate.status(id),'cancelled');});
test('once-only dispatch rejects duplicates and mismatched session/hash',async()=>{const gate=new InputGate();const id=gate.create('s','中');const preview=await gate.prepare(id,async()=>'English');await assert.rejects(gate.submit(id,'other',preview.sourceHash,async()=>0));await assert.rejects(gate.submit(id,'s','bad',async()=>0));let calls=0;await gate.submit(id,'s',preview.sourceHash,async()=>++calls);await assert.rejects(gate.submit(id,'s',preview.sourceHash,async()=>++calls));assert.equal(calls,1);});
test('unknown dispatch outcome is never automatically replayed',async()=>{const gate=new InputGate();const id=gate.create('s','中');const p=await gate.prepare(id,async()=>'English');await assert.rejects(gate.submit(id,'s',p.sourceHash,async()=>{throw new Error('lost ack');}));assert.equal(gate.status(id),'uncertain');await assert.rejects(gate.submit(id,'s',p.sourceHash,async()=>true));});
test('signed source block preserved; newer overlay revision wins',async()=>{const store=new OverlayStore();const original:NativeEvent={id:'e',sessionId:'s',sequence:1,revision:1,type:'progress',text:'Public text',public:true,timestamp:'2026-09-24',raw:{signature:'opaque-signature',content:'public'}};store.ingest(original);const wait=deferred<TranslationResult>();const pending=store.translate('s','e',()=>wait.promise);store.ingest({...original,revision:2,text:'New public text'});wait.resolve(result(original.text));assert.equal(await pending,false);await store.translate('s','e',async t=>result(t));assert.deepEqual((store.get('s','e').source?.raw as any).signature,'opaque-signature');assert.deepEqual(original.raw,{signature:'opaque-signature',content:'public'});});
test('tool approvals and nonpublic payloads never enter overlay translation',async()=>{const store=new OverlayStore();for(const type of ['approval','tool','error'] as const){store.ingest({id:type,sessionId:'s',sequence:1,revision:1,type,text:'native',public:true,timestamp:'now'});await assert.rejects(store.translate('s',type,async t=>result(t)));}});
test('queue deduplicates by immutable key and prioritizes input then final',async()=>{const queue=new TranslationQueue(1);const order:string[]=[];const start=deferred<void>();const first=queue.enqueue('first','progress',()=>start.promise);const p=queue.enqueue('p','progress',async()=>{order.push('progress');return 1;});const f=queue.enqueue('f','final',async()=>{order.push('final');return 2;});const i=queue.enqueue('i','input',async()=>{order.push('input');return 3;});const duplicate=queue.enqueue('i','input',async()=>999);assert.equal(i,duplicate);start.resolve();await Promise.all([first,p,f,i]);assert.deepEqual(order,['input','final','progress']);});

test('input translation fails closed on echoed or partly untranslated Chinese, preserving literal paths',async()=>{
 for(const reply of ['测试，开一个新会话','Open a new session，测试']){
  const translator=new Translator(async()=>new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:reply}}]}),{status:200}));
  await assert.rejects(translator.translate('测试，开一个新会话','input',base,'fixture'),/正文仍含中文/);
 }
 const translator=new Translator(async(_url,init)=>{const body=JSON.parse(String(init?.body));const translated=body.messages.at(-1).content.replace('请检查','Please inspect');return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:translated}}]}),{status:200});});
 assert.equal((await translator.translate('请检查 `中文.txt`','input',base,'literal')).text,'Please inspect `中文.txt`');
});
