import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,readFile,rm,access,link,stat} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {WorktreeService} from '../packages/worktrees';
import {WorkbenchController} from '../apps/desktop/host/controller';import {StateStore,SecretStore} from '../apps/desktop/host/store';import type {Session} from '../packages/contracts';
const run=promisify(execFile),git=async(cwd:string,...args:string[])=>(await run('git',args,{cwd,windowsHide:true})).stdout.trim();
async function fixture(){const root=await mkdtemp(path.join(os.tmpdir(),'awb-retention-')),repo=path.join(root,'repo'),data=path.join(root,'data');await mkdir(repo);await git(repo,'init');await git(repo,'config','user.name','Fixture');await git(repo,'config','user.email','fixture@example.invalid');await git(repo,'config','core.autocrlf','false');await writeFile(path.join(repo,'tracked'),'base');await writeFile(path.join(repo,'.gitignore'),'ignored\n');await git(repo,'add','.');await git(repo,'commit','-m','base');return {root,repo,data,service:new WorktreeService(data),close:()=>rm(root,{recursive:true,force:true})};}

test('maintenance blocks new work and graceful shutdown waits for archive completion',async()=>{const f=await fixture(),store=new StateStore(f.data);await store.load();let release!:()=>void,started!:()=>void;const running=new Promise<void>(resolve=>started=resolve),blocked=new Promise<void>(resolve=>release=resolve);f.service.cleanup=async()=>{started();await blocked;return {archived:[],failed:[]};};const controller=new WorkbenchController(store,new SecretStore(f.data,{encrypt:s=>Buffer.from(s),decrypt:b=>b.toString()}),{worktrees:f.service,pickDirectory:async()=>null,copy:()=>{},openPath:async()=>{},nativeCapabilities:()=>[]},()=>{});try{const maintenance=controller.maintainWorktrees();await running;assert.equal(controller.hasActiveSessionWork(),true);await assert.rejects(controller.call('session/fork',{sessionId:'missing'}),/WORKTREE_BUSY/);let closed=false;const closing=controller.dispose().then(()=>{closed=true;});await new Promise(resolve=>setTimeout(resolve,25));assert.equal(closed,false);release();await maintenance;await closing;assert.equal(closed,true);}finally{release();await controller.dispose();await f.close();}});

test('controller protects viewed and pinned sessions, refuses active work and restores archived session records',async()=>{const f=await fixture(),store=new StateStore(f.data);await store.load();const controller=new WorkbenchController(store,new SecretStore(f.data,{encrypt:s=>Buffer.from(s),decrypt:b=>b.toString()}),{worktrees:f.service,pickDirectory:async()=>null,copy:()=>{},openPath:async()=>{},nativeCapabilities:()=>[]},()=>{});try{const records=[await f.service.create(f.repo)];records.push(await f.service.create(f.repo),await f.service.create(f.repo));await store.update(s=>{s.sessions=records.map((worktree,i):Session=>({id:'s'+i,title:'Fixture '+i,pinned:i===1,archived:false,group:'',createdAt:'2026-09-28T00:00:00Z',projectId:null,projectPath:worktree.cwd,worktree,binding:{runtime:'demo',provider:'offline',accountRef:'none',executionId:'local-device',egress:'demo'},status:'idle',messages:[]}));});await controller.call('worktrees/configure',{autoDelete:true,limit:1});await controller.call('navigation/view',{sessionId:'s0'});const result=await controller.call('worktrees/cleanup') as {archived:string[]};assert.deepEqual(result.archived,[records[2]!.id]);await access(records[0]!.path);await access(records[1]!.path);assert.equal(store.snapshot().sessions[2]!.worktree?.status,'archived');await controller.call('worktrees/restore',{id:records[2]!.id});assert.equal(store.snapshot().sessions[2]!.worktree?.status,'ready');await access(records[2]!.path);for(const status of ['running','uncertain'] as const){await store.update(s=>{s.sessions[0]!.status=status;});await assert.rejects(controller.call('worktrees/cleanup'),/WORKTREE_BUSY/);}await store.update(s=>{s.sessions[0]!.status='idle';});await controller.call('draft/prepare',{sessionId:'s0',text:(await controller.call('demo.sample/get') as {input:string}).input,demo:true});await assert.rejects(controller.call('worktrees/cleanup'),/WORKTREE_BUSY/);}finally{await controller.dispose();await f.close();}});
test('retention snapshots dirty, staged, untracked, ignored bytes and restores an unpushed commit',async()=>{const f=await fixture();try{
 const first=await f.service.create(f.repo),second=await f.service.create(f.repo);await writeFile(path.join(first.path,'committed'),'unpushed');await git(first.path,'add','.');await git(first.path,'commit','-m','private fixture commit');const head=await git(first.path,'rev-parse','HEAD');await writeFile(path.join(first.path,'tracked'),'staged');await git(first.path,'add','tracked');await writeFile(path.join(first.path,'tracked'),'unstaged');await writeFile(path.join(first.path,'untracked'),'new');await writeFile(path.join(first.path,'ignored'),'ignored bytes');await mkdir(path.join(first.path,'empty'));const index=await git(first.path,'diff','--cached'),source=await git(f.repo,'status','--porcelain');
 await f.service.configure(undefined,{autoDelete:true,limit:1});assert.deepEqual((await f.service.cleanup([second.id])).archived,[first.id]);await assert.rejects(access(first.path));assert.equal(await git(f.repo,'status','--porcelain'),source);const archived=(await f.service.list()).records.find(r=>r.id===first.id)!;assert.equal(archived.status,'archived');assert.equal(await git(f.repo,'rev-parse',archived.archive!.ref),head);
 const restarted=new WorktreeService(f.data),restored=await restarted.restore(first.id);assert.equal(restored.status,'ready');assert.equal(await git(first.path,'rev-parse','HEAD'),head);assert.equal(await git(first.path,'diff','--cached'),index);assert.equal(await readFile(path.join(first.path,'tracked'),'utf8'),'unstaged');assert.equal(await readFile(path.join(first.path,'untracked'),'utf8'),'new');assert.equal(await readFile(path.join(first.path,'ignored'),'utf8'),'ignored bytes');await access(path.join(first.path,'empty'));await restarted.validate(restored);await assert.rejects(f.service.restore(first.id),/TARGET_EXISTS/);
}finally{await f.close();}});
test('disabled cleanup and protected IDs keep all checkouts; nested repositories fail closed',async()=>{const f=await fixture();try{
 const first=await f.service.create(f.repo),second=await f.service.create(f.repo);assert.deepEqual(await f.service.cleanup(),{archived:[],failed:[]});await f.service.configure(undefined,{autoDelete:true,limit:1});assert.deepEqual(await f.service.cleanup([first.id,second.id]),{archived:[],failed:[]});await mkdir(path.join(first.path,'nested','.git'),{recursive:true});const result=await f.service.cleanup([second.id]);assert.equal(result.archived.length,0);assert.equal(result.failed[0]?.id,first.id);await access(first.path);await assert.rejects(f.service.configure(undefined,{limit:0}),/SETTINGS_INVALID/);
}finally{await f.close();}});
test('archive corruption prevents restoration without creating or overwriting a checkout',async()=>{const f=await fixture();try{const first=await f.service.create(f.repo),second=await f.service.create(f.repo);await f.service.configure(undefined,{autoDelete:true,limit:1});await f.service.cleanup([second.id]);const saved=(await f.service.list()).records.find(r=>r.id===first.id)!;await writeFile(saved.archive!.file,'corrupt');await assert.rejects(f.service.restore(first.id),/CHECKSUM/);await assert.rejects(access(first.path));}finally{await f.close();}});

test('archive preserves hardlinked bytes without altering aliases outside the checkout',async()=>{const f=await fixture();try{
 const first=await f.service.create(f.repo),second=await f.service.create(f.repo),outside=path.join(f.root,'outside.txt');
 await writeFile(outside,'shared bytes');await link(outside,path.join(first.path,'linked.txt'));
 await f.service.configure(undefined,{autoDelete:true,limit:1});assert.deepEqual((await f.service.cleanup([second.id])).archived,[first.id]);
 assert.equal(await readFile(outside,'utf8'),'shared bytes');await f.service.restore(first.id);
 assert.equal(await readFile(path.join(first.path,'linked.txt'),'utf8'),'shared bytes');assert.equal((await stat(path.join(first.path,'linked.txt'))).nlink,1);
 await writeFile(outside,'external edit');assert.equal(await readFile(path.join(first.path,'linked.txt'),'utf8'),'shared bytes');
}finally{await f.close();}});
