import {RememberedDetails} from './UiMemory';
import type {AccountSetupPlan} from '../../../packages/remote-account-catalog/setup';
import {Modal} from './ui';
const labels:Record<string,string>={CLI_RELEASE_UNAVAILABLE:'未能核实官方最新版，请检查 VPS 出网后重新检查；不会安装旧版本冒充最新版。',SETUP_RECHECK_REQUIRED:'此次配置未确认完成。请重新检查实际状态，再预览下一次操作。',CLI_PLATFORM_UNSUPPORTED:'此系统或架构暂无已验证的安装包，未尝试安装。',CLI_INSTALL_CONFLICT:'共享 CLI 安装位置已有不同内容，请核对；不会覆盖。',ADMIN_REQUIRED:'请使用 root 管理连接。',SYSTEMD_REQUIRED:'此主机没有可用的 systemd，暂不能按当前方式托管统一服务。',POLICY_CONFLICT:'发现不同的工作空间权限来源，需要先核对现有控制服务。',POLICY_REQUIRED:'现有工作空间控制服务尚未发布账号权限策略。',HOST_KEY_REQUIRED:'缺少可核实的 SSH 公开主机标识。',OWNER_CONFLICT:'同名服务身份已被其他用途占用，未作修改。',EXISTING_DEPLOYMENT_CHANGED:'已有统一服务文件与此版本不同，未覆盖。请核对原部署版本。',EXISTING_SERVICE_UNAVAILABLE:'已发现统一服务，但未取得有效回执。请检查该服务的运行状态。',UNSAFE_DEPLOYMENT:'部署目录的归属或权限不符合要求，未作修改。',NATIVE_CLI_REQUIRED:'未找到受支持且可共享执行的原生 CLI。请先安装或准备至少一家 CLI，再重新检查。',PREFLIGHT_FAILED:'未完成主机条件检查，请检查连接后重试。'};
function message(code:string){for(const provider of ['codex','claude']){const name=provider==='codex'?'Codex':'Claude',suffix=provider.toUpperCase();if(code==='CLI_MISSING_'+suffix)return `在已检查的位置未找到可用的 ${name} CLI，可在本次配置中安装。`;if(code==='CLI_NOT_SHARED_'+suffix)return `已发现 ${name} CLI，但位于 root 私有目录。将另行准备共享安装，保留原安装和登录。`;if(code==='CLI_UNTRUSTED_'+suffix)return `已发现 ${name} CLI，但文件或上级目录的所有者/权限不适合统一服务。将保留原安装，另行安装官方版本。`;if(code==='CLI_PROBE_FAILED_'+suffix)return `${name} CLI 位置或版本核实失败，请查看已发现的安装；可配置独立官方版本。`;if(code==='CLI_VERSION_'+suffix)return `${name} CLI 未返回可核实的版本。`;}return labels[code]??'未完成部署条件检查，请核对主机状态。';}
export default function AccountSetup({plan,busy,error,onClose,onApply,onRecheck}:{plan:AccountSetupPlan;busy:boolean;error:string;onClose:()=>void;onApply:()=>void;onRecheck:()=>void}){
 return <Modal title="准备统一账号服务" subtitle="Codex 与 Claude 共用管理入口，账号各自保留一处原生认证。" className="account-setup-modal" onClose={onClose}><div className="account-setup-content">
 {plan.status==='ready'?<p>统一服务已经接通，可返回账号页完成登录与分配。</p>:<><p>{plan.status==='installable'?'检查已完成。确认后将准备以下内容：':'检查发现以下待处理事项：'}</p>{plan.blockers.map(code=><p className="inline-error" key={code}>{message(code)}</p>)}{plan.status==='installable'&&<ul><li>{plan.createOwner?'创建':'复用'}专用低权限身份 <code>{plan.owner}</code>，集中保管原生登录。</li><li>安装并启动工作台账号服务，使用已核实或本次安装的 CLI。</li><li>沿用现有工作空间权限来源，账号使用权仍在工作空间页分配。</li></ul>}{plan.warnings.map(code=><p className="inline-note" key={code}>{message(code)}</p>)}{!!plan.detected?.length&&<div className="account-cli-detected" data-testid="account-cli-detected"><h4>已发现的安装</h4>{plan.detected.map((item,index)=><p className="inline-note" key={index}>{item.provider==='codex'?'Codex':'Claude'}{item.version?' '+item.version:''} · {{ready:'可共享使用',private:'root 私有安装', 'version-mismatch':'版本待适配',untrusted:'路径权限待核实',unverified:'未能核实版本'}[item.status]}<code>{item.path}</code></p>)}</div>}{!!plan.downloads?.length&&<div className="account-cli-downloads" data-testid="account-cli-downloads"><h4>一键配置包含 · 官方最新版</h4>{plan.downloads.map(item=><p key={item.provider}><strong>{item.provider==='codex'?'Codex':'Claude'} {item.version}</strong> · 约 {Math.ceil(item.size/1048576)} MB<br/><span className="inline-note">调用官方原生安装器，校验发布包后准备独立共享程序。</span></p>)}<p className="inline-note">确认后下载并配置两家所需组件。下载失败会显示原因，可重新检查；不会修改 root 原安装或登录。</p></div>}<RememberedDetails memoryId="AccountSetup.details.1"><summary>查看接入位置</summary><dl>{Object.entries(plan.binaries).map(([provider,value])=><div key={provider}><dt>{provider==='codex'?'Codex':'Claude'} CLI</dt><dd>{value}</dd></div>)}{plan.paths.map(value=><div key={value}><dt>服务位置</dt><dd>{value}</dd></div>)}{plan.policyPath&&<div><dt>工作空间权限</dt><dd>{plan.policyPath}</dd></div>}</dl></RememberedDetails><p className="inline-note">不会读取或复制原账号凭据、删除工作空间、替换现有 CLI，也不会启动模型任务。准备完成后，由你集中完成官方登录。</p></>}
 {error&&<p className="inline-error" role="alert">{error}</p>}</div><div className="account-setup-actions account-setup-footer"><button className="button secondary" disabled={busy} onClick={onClose}>{plan.status==='ready'?'返回账号页':'取消'}</button>{plan.status!=='ready'&&<button className="button secondary" disabled={busy} onClick={onRecheck}>重新检查</button>}{plan.status==='installable'&&<button className="button primary" data-testid="account-service-confirm" disabled={busy} onClick={onApply}>{busy?'正在配置…':plan.downloads?.length?'确认一键配置':'确认准备统一服务'}</button>}</div></Modal>;
}
