import {RememberedDetails} from './UiMemory';
import {useUiPreference} from './ui-preferences';
import { useEffect, useState } from 'react';
import type { ModelPrice, ModelUsageGroup, ModelUsageSummary as Summary, UsagePeriod, UsageScope } from '../../../packages/model-management/types';
import { api } from './App';
import { Icon, errorText } from './ui';
import './ModelManagement.css';

const periods: [UsagePeriod, string][] = [['1day','1 day'],['7day','7 day'],['cycle','本周期'],['month','本月']];
const count = (n: number | null) => n === null ? '—' : n.toLocaleString('zh-CN');
const dollars = (n: number | null) => n === null ? '—' : '$' + n.toLocaleString('en-US', { maximumFractionDigits: 4, minimumFractionDigits: 2 });
const costLabel = (value?: {estimatedUsd:number|null;lowerBoundUsd?:number|null}) => value?.estimatedUsd != null ? dollars(value.estimatedUsd) : value?.lowerBoundUsd != null ? '至少 ' + dollars(Math.floor(value.lowerBoundUsd * 1e4) / 1e4) : '—';
function PriceEditor({ group, scope, saved }: { group: ModelUsageGroup; scope: UsageScope; saved(): void }) {
  const [draft,setDraft]=useState<Record<string,string>>(()=>Object.fromEntries(['input','output','cacheRead','cacheWrite'].map(k=>[k,String(group.price?.[k as keyof ModelPrice]??'')]))),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const save=async()=>{if(busy)return;setBusy(true);setError('');try{const price=Object.fromEntries(Object.entries(draft).filter(([,v])=>v!=='').map(([k,v])=>[k,Number(v)]));await api('models/pricing/save',{scope,model:group.model,revision:group.priceRevision,price});saved();}catch(e){setError(errorText(e)==='MODEL_PRICE_CHANGED'?'单价已在其他位置更新，请刷新后重试。':errorText(e)==='MODEL_PRICE_INVALID'?'请填写有效的输入和输出单价。':errorText(e));}finally{setBusy(false);}};
  return <RememberedDetails memoryId="ModelUsageSummary.details.1" scope={JSON.stringify([scope,group.model])} className="model-price-editor"><summary>{group.price?'调整单价':'设置单价'}<small>USD / 1M tokens</small></summary><div className="model-price-inputs">{([['input','输入'],['output','输出'],['cacheRead','缓存读取'],['cacheWrite','缓存写入']] as const).map(([key,label])=><label key={key}>{label}<input aria-label={group.model+' '+label+'单价'} type="number" min="0" step="any" disabled={busy} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})} placeholder={key.startsWith('cache')?'同输入单价':'必填'}/></label>)}<button className="text-button" disabled={busy} onClick={()=>void save()}>保存</button></div><small>{group.priceSource==='reference'?'官方参考单价 · 2026-09-29 核对。OpenAI 按短上下文标准档；Claude 按全球标准档、5 分钟缓存写入。':group.priceSource==='manual'?'使用此来源的自定义单价。':''}按当前单价估算；未单列缓存价格时按输入单价计。不含工具费、税费或套餐订阅费。</small>{error&&<p role="alert" className="inline-error">{error}</p>}</RememberedDetails>;
}
export default function ModelUsageSummary({scope,refreshKey}:{scope:UsageScope;refreshKey?:string}){
  const [preferredPeriod,setPeriod]=useUiPreference<UsagePeriod>('usage.period',JSON.stringify(scope)),[value,setValue]=useState<Summary>(),[expanded,setExpanded]=useUiPreference<boolean>('usage.expanded',JSON.stringify(scope)),[error,setError]=useState(''),[version,setVersion]=useState(0);
  const translation=scope.kind==='translation',period=translation&&preferredPeriod==='cycle'?'7day':preferredPeriod;
  const missingPrices=value?.groups.filter(group=>group.estimatedUsd===null&&!group.price).length??0;
  useEffect(()=>{let live=true;setValue(undefined);setError('');void api<Summary>('models/usage',{scope,period}).then(v=>{if(live)setValue(v);},e=>{if(live)setError(errorText(e));});return()=>{live=false;};},[scope.kind,scope.id,period,refreshKey,version]);
  return <section className="model-usage-summary" data-testid={'model-usage-'+scope.id} aria-label={translation?'翻译用量统计':'用量统计'}><div className="model-usage-toolbar"><span>{translation?'翻译用量':'用量统计'}</span><div className="model-periods" role="group" aria-label="统计时段">{periods.filter(([key])=>!translation||key!=='cycle').map(([key,label])=><button type="button" key={key} aria-pressed={period===key} disabled={key==='cycle'&&scope.kind==='api'} title={key==='cycle'?(scope.kind==='api'?'API 没有官方额度周期':'优先按周额度重置周期；没有周窗口时按 5h 窗口') : key==='1day'?'最近 24 小时':key==='7day'?'最近 7 天':'本机时区自然月'} onClick={()=>setPeriod(key)}>{label}</button>)}</div></div><button type="button" className="model-usage-total" aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}><div><strong>{value?.cycleUnavailable?'—':count(value?.totalTokens??null)}</strong><small>{value?.incomplete.includes('totalTokens')?'已知 tokens · 数据不完整':'tokens'}</small></div><div><strong>{costLabel(value?.cycleUnavailable?undefined:value)}</strong><small>API 等价估算</small></div><Icon name="chevron" size={14}/></button>
    {value?.cycleUnavailable&&<p className="model-usage-note">尚未观测到完整重置周期。读取到额度恢复 100% 或原生窗口轮换后开始计入。</p>}
    {value&&value.unpricedModels>0&&!value.cycleUnavailable&&<p className="model-usage-note">{missingPrices>0?`${missingPrices} 个模型缺少单价，可在详情中设置。`:''}{value.unpricedModels>missingPrices?'部分计费用量未上报。':''}{value.lowerBoundUsd!=null?'金额为已知用量的保守下界，未知部分未计为零。':'暂无法估算。'}</p>}
    {expanded&&value&&!value.cycleUnavailable&&<div className="model-usage-models">{value.groups.map(group=><article className="model-usage-model" key={group.model}><div className="model-usage-model-name"><strong>{group.model||'未标明模型'}</strong><span>{costLabel(group)}</span></div>{group.estimatedUsd===null&&<p className="model-usage-note">{!group.price?'此模型尚无单价，请在下方设置。':group.lowerBoundUsd!=null?'部分计费用量未上报，先显示可确认的最低金额。':'尚无可计价的用量明细。'}</p>}<dl>{([['inputTokens','输入'],['outputTokens','输出'],['cacheReadTokens','缓存读取'],['cacheWriteTokens','缓存写入']] as const).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{count(group[key])}{group.incomplete.includes(key)&&group[key]!==null?' +':''}</dd></div>)}<div><dt>缓存命中率</dt><dd>{group.cacheHitRate===null?'—':(group.cacheHitRate*100).toFixed(1)+'%'}</dd></div><div><dt>总 tokens</dt><dd>{count(group.totalTokens)}</dd></div></dl>{group.model&&<PriceEditor key={group.model+group.priceRevision} group={group} scope={scope} saved={()=>setVersion(v=>v+1)}/>}</article>)}{!value.groups.length&&<p className="model-usage-note">此时段尚无工作台用量记录。</p>}<p className="model-usage-note">仅统计此工作台收到的用量。输入已包含缓存，合计不重复相加。{value.partialHistory?'部分历史没有用量回执。':''}“+”表示已知下界；“—”表示未知；“至少”按缺失分类的最低适用单价估算，不是完整账单。</p></div>}
    {error&&<p className="inline-error" role="alert">{error}<button className="text-button" onClick={()=>setVersion(v=>v+1)}>重试</button></p>}
  </section>;
}
