import {useUiPreference} from './ui-preferences'; import {coreTranslationLayouts} from '../../../packages/translation/layouts';
import { useEffect, useState } from 'react';
import type { PluginRecord, PluginAppearance } from '../../../packages/plugins-core';
import { api } from './App';
import { Icon, Modal, Toggle } from './ui';
import type { PageProps } from './Pages';
import TranslationSettings from './TranslationSettings';
import NativePluginSettings from './NativePluginSettings';
import PluginImportDialog from './PluginImportDialog';
import './NativeResources.css';
import './ReadingPane.css';

export function PluginAppearanceLayer() {
  const [appearance, setAppearance] = useState<PluginAppearance>({ variables: {} });
  useEffect(() => { let active = true; const refresh = () => { void api<PluginAppearance>('extensions/appearance').then(value => { if (active) setAppearance(value); }).catch(() => { if (active) setAppearance({ variables: {} }); }); }; refresh(); const unsubscribe = window.workbench?.onExtensions?.(refresh); return () => { active = false; unsubscribe?.(); }; }, []);
  useEffect(() => { const element = document.documentElement, before = new Map<string, string>(); for (const [key, value] of Object.entries(appearance.variables)) { before.set(key, element.style.getPropertyValue(key)); element.style.setProperty(key, value); } return () => { for (const [key, value] of before) value ? element.style.setProperty(key, value) : element.style.removeProperty(key); }; }, [appearance]);
  return appearance.background ? <div aria-hidden="true" className="plugin-background" data-testid="plugin-background" style={{ backgroundImage: `url("${appearance.background}")`, opacity: appearance.opacity }}/> : null;
}
export default function PluginSettings(props: PageProps) {
  const { state, refresh, report, notify } = props;
  const [tab, setTab] = useUiPreference<'workbench' | 'runtime'>('settings.plugins-tab');
  const [importOpen, setImportOpen] = useState(false);
  const [translationOn, setTranslationOn] = useState(state.plugins?.translation?.enabled !== false);
  useEffect(() => setTranslationOn(state.plugins?.translation?.enabled !== false), [state.plugins?.translation?.enabled]);
  const [records, setRecords] = useState<PluginRecord[]>([]), [busy, setBusy] = useState(false), [expanded, setExpanded] = useUiPreference<string[]>('plugins.expanded'), [approval, setApproval] = useState<PluginRecord | null>(null);
  const reload = async () => setRecords(await api<PluginRecord[]>('extensions/list'));
  useEffect(() => { const update = () => { void reload().catch(report); }; update(); return window.workbench?.onExtensions?.(update); }, []);
  const action = async (fn: () => Promise<unknown>) => { if (busy) return; setBusy(true); try { await fn(); await reload(); } catch (e) { report(e); await reload().catch(() => {}); } finally { setBusy(false); } };
  const expand = (id: string) => setExpanded(value => value.includes(id) ? value.filter(item => item !== id) : [...value, id]);
  const importPlugin = async (file?: File) => { const result = file ? await window.workbench.importPluginFile(file) : await api('extensions/import'); if (!result) return false; await reload(); notify('插件已导入，默认关闭'); return true; };
  const toggle = (record: PluginRecord, enabled: boolean) => { if (enabled && (record.manifest.main || record.manifest.renderer) && !record.approved) { setApproval(record); return; } setRecords(values => values.map(value => value.manifest.id === record.manifest.id ? {...value,enabled} : value)); void action(() => api('extensions/toggle', { id: record.manifest.id, hash: record.hash, enabled })); };
  return <div className="native-resources" data-testid="plugins-settings">
    {importOpen && <PluginImportDialog onClose={() => setImportOpen(false)} onImport={importPlugin}/>}
    <div className="skill-list-toolbar plugin-tabs-toolbar"><div className="skill-tabs" role="tablist" aria-label="插件类型">{(['workbench', 'runtime'] as const).map(value => <button key={value} id={`plugin-tab-${value}`} role="tab" aria-selected={tab === value} aria-controls={`plugin-panel-${value}`} tabIndex={tab === value ? 0 : -1} onClick={() => setTab(value)} onKeyDown={event => { if (!['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(event.key)) return; event.preventDefault(); const next = event.key === 'Home' ? 'workbench' : event.key === 'End' ? 'runtime' : value === 'workbench' ? 'runtime' : 'workbench'; setTab(next); document.getElementById(`plugin-tab-${next}`)?.focus(); }}>{value === 'workbench' ? '工作台插件' : '运行时插件'}</button>)}</div>{tab === 'workbench' && <button className="button secondary" data-testid="plugin-import" disabled={busy} onClick={() => setImportOpen(true)}><Icon name="plus" size={15}/>导入 ZIP</button>}</div>
    {tab === 'workbench' ? <section role="tabpanel" id="plugin-panel-workbench" aria-labelledby="plugin-tab-workbench">
    <article className="plugin-row" data-testid="translation-plugin"><header><button aria-expanded={expanded.includes('translation')} data-testid="translation-plugin-expand" onClick={() => expand('translation')}><h2><Icon name="globe" size={16}/> 双语工作流</h2><p>独立翻译输入、公开进度和最终回复。<span className="outline-label">内置</span></p></button><fieldset disabled={busy} className="resource-fieldset"><Toggle label="启用双语工作流" checked={translationOn} onChange={enabled => { setTranslationOn(enabled); void action(async () => { try { await api('plugins/set-enabled', { id: 'translation', enabled }); await refresh(); } catch(error) {setTranslationOn(state.plugins?.translation?.enabled !== false);throw error;} }); }}/></fieldset></header>{expanded.includes('translation') && <div className="plugin-expanded"><fieldset className="resource-fieldset" disabled={busy}><Toggle label="显示临时翻译开关" description="在会话框左下角临时暂停或恢复翻译，状态全局记忆。隐藏时恢复翻译，保留上次临时状态。" checked={state.translationQuickToggle?.show !== false} onChange={show => void action(async () => { await api('translation/quick-toggle', { show }); await refresh(); })}/></fieldset><fieldset data-workbench-translation-layout className="translation-layout-setting" disabled={busy}><legend>译文的阅读位置</legend><div className="translation-layout-options">{(state.translationLayouts??coreTranslationLayouts).map(option=><label key={option.id}><input type="radio" name="translation-layout" value={option.id} checked={(state.translationLayout??'panel')===option.id} onChange={()=>void action(async()=>{await api('translation/layout',{layout:option.id});await refresh();})}/>{option.label}</label>)}</div>{state.translationLayout&&!((state.translationLayouts??coreTranslationLayouts).some(item=>item.id===state.translationLayout))&&<p role="status">所选阅读扩展暂不可用，当前使用右侧对照；偏好已保留。</p>}<button type="button" className="text-button" data-testid="translation-seamless" onClick={()=>void action(async()=>{await api('translation/seamless');await refresh();})}>启用无感模式</button><p>{state.translationLayout==='translated-only'?'优先显示中文译文；译文未就绪或失败时保留原文。':state.translationLayout==='inline'?'中文译文始终跟在对应消息下方，右侧留给文件与子会话。':'默认在右侧对照阅读。打开文件或子会话时，已有和后续译文自动移到对应消息下方。'}Subagent 消息仅在点击翻译图标后翻译。</p></fieldset><TranslationSettings {...props} moduleEnabled={translationOn}/></div>}</article>
    {records.map(record => <article className="plugin-row" key={record.manifest.id} data-testid={`plugin-${record.manifest.id}`}><header><button aria-expanded={expanded.includes(record.manifest.id)} onClick={() => expand(record.manifest.id)}><h2>{record.manifest.name}</h2><p>{record.manifest.description} <span className="outline-label">个人 · {record.manifest.version}</span></p></button><fieldset disabled={busy} className="resource-fieldset"><Toggle label={`启用 ${record.manifest.name}`} checked={record.enabled} onChange={enabled => toggle(record, enabled)}/></fieldset></header>{expanded.includes(record.manifest.id) && <div className="plugin-expanded"><div className="plugin-capabilities">{record.manifest.capabilities.map(cap => <span className="outline-label" key={cap}>{cap === 'context' ? '模型上下文' : cap === 'theme' ? '颜色与背景' : '完整代码权限'}</span>)}</div><p className="resource-native-path mono">{record.directory}</p>{record.error && <p className="inline-error">{record.error === 'PLUGIN_RENDERER_ACTIVATION_FAILED' ? '界面入口加载失败，已恢复基础界面；请检查插件后重新启用。' : record.error}</p>}<button className="button secondary" disabled={busy} onClick={() => void action(async () => { if (await api('extensions/export', { id: record.manifest.id, hash: record.hash })) notify('插件 ZIP 已导出'); })}>导出插件 ZIP</button></div>}</article>)}
    <p className="inline-note plugin-list-note" data-testid="plugin-list-note">工作台插件可扩展界面、上下文和工作流程，支持 ZIP 导入与分享。开发接口及示例见 docs/36-workbench-plugin-api.md。</p>
    </section> : <section role="tabpanel" id="plugin-panel-runtime" aria-labelledby="plugin-tab-runtime"><NativePluginSettings notify={notify}/></section>}
    {approval && <Modal title="启用具有完整代码权限的插件？" onClose={() => setApproval(null)}><p className="dialog-copy">“{approval.manifest.name}”可运行宿主或界面代码，调用工作台服务、读写本机文件、使用网络，并替换整个工作台界面。宿主代码不在沙箱中。仅启用你信任且已检查过的代码。</p><p className="mono resource-native-path">包摘要：{approval.hash}</p><div className="modal-actions"><button className="button secondary" onClick={() => setApproval(null)}>取消</button><button className="button primary" data-testid="plugin-approve-host" disabled={busy} onClick={() => void action(async () => { await api('extensions/toggle', { id: approval.manifest.id, hash: approval.hash, enabled: true, approveHost: true }); setApproval(null); })}>信任此版本并启用</button></div></Modal>}
  </div>;
}
