import {useEffect,useRef,useState} from 'react';
import type {SshHost,SharedAccount} from '../../../packages/contracts';
import type {BrowserLogin,BrowserProfile,RemoteBrowserState,BrowserSetupPlan,BrowserControlResult} from '../../../packages/remote-account-catalog/browser';
import {api} from './App';
import {Icon,Modal,errorText} from './ui';
import SelectMenu from './SelectMenu';
import './RemoteBrowserManager.css';
const states={preparing:'正在准备远端浏览器', 'awaiting-browser':'请在远端浏览器完成授权',authenticated:'Claude 原生登录已核实',cancelled:'本次登录已取消',expired:'本次登录等待已超时',failed:'本次登录未完成'};
export default function RemoteBrowserManager({host,account,draftLogin=false,notify}:{host:SshHost;account?:SharedAccount;draftLogin?:boolean;notify:(v:string)=>void}){
 const loginMode=!!account||draftLogin;
 const [value,setValue]=useState<RemoteBrowserState>(),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[job,setJob]=useState<BrowserLogin>(),[code,setCode]=useState('');
 const [setup,setSetup]=useState<BrowserSetupPlan>();
 const [closeBrowser,setCloseBrowser]=useState(false);
 const [edit,setEdit]=useState<{key?:string;label:string}>(),[remove,setRemove]=useState<BrowserProfile>();
 const live=useRef(true),lock=useRef(false),currentJob=useRef<BrowserLogin>(undefined);
 const apply=(v:BrowserLogin)=>{currentJob.current=v;if(live.current)setJob(v);};
 useEffect(()=>{live.current=true;void refresh();return()=>{live.current=false;const j=currentJob.current;if(j&&j.cleanup!=='confirmed')void api('remote-browser/cancel',{id:host.id,jobId:j.jobId}).catch(()=>{});};},[]);
 const active=!!job&&(['preparing','awaiting-browser'].includes(job.state)||job.cleanup==='pending');
 useEffect(()=>{if(!active||!job)return;let cancelled=false;let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const v=await api<BrowserLogin>('remote-browser/status',{id:host.id,jobId:job.jobId});if(!cancelled){apply(v);if(v.state==='authenticated'&&v.cleanup==='confirmed')notify('Claude 登录成功，本次浏览器与登录进程已关闭。');}}catch(e){if(!cancelled)setError(errorText(e));}if(!cancelled)timer=setTimeout(()=>void poll(),1200);};timer=setTimeout(()=>void poll(),800);return()=>{cancelled=true;clearTimeout(timer);};},[job?.jobId,active]);
 async function run(fn:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await fn();}catch(e){if(live.current)setError(errorText(e));}finally{lock.current=false;if(live.current)setBusy(false);}}
 async function refresh(){return run(async()=>{const v=await api<RemoteBrowserState>('remote-browser/profiles',{id:host.id});if(live.current){setValue(v);setSelected(old=>v.profiles.some(p=>p.key===old)?old:'');}});}
 async function mutate(action:'create'|'rename'|'delete'){return run(async()=>{const v=await api<RemoteBrowserState>('remote-browser/'+action,{id:host.id,...(action==='delete'?{key:remove?.key,confirm:true}:edit)});if(live.current){setValue(v);setEdit(undefined);setRemove(undefined);if(!v.profiles.some(p=>p.key===selected))setSelected('');notify(action==='delete'?'浏览器用户已删除。':'浏览器用户已保存。');}});}
 async function start(){return run(async()=>{
  const target=account??(draftLogin?await api<SharedAccount>('native-accounts/prepare-claude',{id:host.id}):undefined);if(!target)return;
  if(!live.current){if(draftLogin)await api('native-accounts/discard-claude',{id:host.id,accountId:target.id});return;}
  let v:BrowserLogin;
  try{v=await api<BrowserLogin>('remote-browser/start',{id:host.id,accountId:target.id,profileKey:selected});}
  catch(error){if(draftLogin)try{await api('native-accounts/discard-claude',{id:host.id,accountId:target.id});}catch{throw Error(errorText(error)+'；临时登录清理未确认，请刷新服务状态。');}throw error;}
  apply(v);
  if(!live.current)await api('remote-browser/cancel',{id:host.id,jobId:v.jobId});
 });}
 async function jobAction(action:'open'|'cancel'|'code'){return run(async()=>{if(!job)return;const supplied=code;setCode('');const v=await api<BrowserLogin|undefined>('remote-browser/'+action,{id:host.id,jobId:job.jobId,...(action==='code'?{code:supplied}:{})});if(v)apply(v);});}
 async function control(action:'launch'|'reconnect'|'stop',profileKey?:string){return run(async()=>{
  const result=await api<BrowserControlResult>('remote-browser/'+action,{id:host.id,...(profileKey?{profileKey}:{}),...(action==='stop'?{confirm:true}:{})});
  if(live.current){setCloseBrowser(false);notify(result.running?'已打开远端浏览器操控。':'浏览器已关闭，用户配置和登录状态保留。');}
 });}
 return <section className="remote-browser" data-testid="remote-browser-manager"><div className="remote-browser-heading"><div className="browser-control-bar">{!loginMode&&value&&<div className="remote-browser-buttons"><button className="button secondary" data-testid="browser-reconnect" disabled={busy||active||!value.installed} onClick={()=>void control('reconnect')}><Icon name="refresh" size={14}/>恢复连接</button><button className="text-button" data-testid="browser-stop" disabled={busy||active} onClick={()=>setCloseBrowser(true)}>关闭浏览器</button></div>}</div><button className="icon-button" aria-label="刷新浏览器用户" disabled={busy||active} onClick={()=>void refresh()}><Icon name="refresh"/></button></div>
 {!value&&<p className="inline-note">{busy?'正在读取远端浏览器…':'尚未读取浏览器状态。'}</p>}
 {value&&!value.installed&&<div className="remote-browser-empty"><h4>浏览器组件缺失</h4><ul>{value.missing.map(p=><li key={p}>{p}</li>)}</ul><button className="button secondary" disabled={busy} onClick={()=>void run(async()=>{const p=await api<BrowserSetupPlan>('remote-browser/setup-plan',{id:host.id});if(live.current)setSetup(p);})}>检查并预览安装方案</button></div>}

 {value?.installed&&<><div className="remote-browser-toolbar"><span>{value.profiles.length} 个浏览器用户</span><button className="text-button" data-testid="browser-profile-create" disabled={busy||active} onClick={()=>setEdit({label:''})}><Icon name="plus" size={14}/>新增用户</button></div>
 {!value.profiles.length&&<p className="inline-note">先创建一个浏览器用户，首次使用时在远端浏览器登录网站账号。</p>}
 <div className="browser-profiles">{value.profiles.map(p=><div className="browser-profile" key={p.key}><Icon name="user" size={17}/><div><strong>{p.label}</strong>{!p.available&&<small>配置缺失</small>}</div>{!loginMode&&<button className="text-button browser-profile-launch" aria-label={`启动并打开 ${p.label}`} disabled={busy||active||!p.available} onClick={()=>void control('launch',p.key)}>启动并打开</button>}<button className="text-button" aria-label={`改名 ${p.label}`} disabled={busy||active} onClick={()=>setEdit({key:p.key,label:p.label})}>改名</button><button className="icon-button" aria-label={`删除 ${p.label}`} disabled={busy||active} onClick={()=>setRemove(p)}><Icon name="trash" size={16}/></button></div>)}</div>
 {loginMode?<div className="remote-browser-start"><label>本次登录使用</label><SelectMenu testId="claude-browser-profile" label="浏览器用户" value={selected} options={value.profiles.map(p=>({value:p.key,label:p.label,disabled:!p.available}))} onChange={setSelected} placeholder="请选择浏览器用户" disabled={busy||active}/><button className="button primary" data-testid="claude-browser-start" disabled={!selected||busy||active||job?.cleanup==='unconfirmed'||job?.state==='authenticated'} onClick={()=>void start()}>启动远端登录</button></div>:null}</>}
 {job&&<div className="remote-browser-progress" role="status"><strong>{states[job.state]}</strong><p>{job.cleanup==='confirmed'?'本次进程已关闭，浏览器用户配置保留。':job.cleanup==='unconfirmed'?'进程清理尚未确认，请核对后再开始下一次登录。':'结束登录后会关闭本次启动的浏览器、显示服务与连接。'}</p><div className="remote-browser-buttons"><button className="button secondary" data-testid="claude-browser-open" disabled={busy||!job.viewerReady} onClick={()=>void jobAction('open')}>打开实时远端浏览器</button>{job.cleanup!=='confirmed'&&<button className="text-button" disabled={busy} onClick={()=>void jobAction('cancel')}>{busy?'正在处理…':'结束并关闭本次进程'}</button>}</div>{job.codeRequested&&<form className="remote-browser-code" onSubmit={e=>{e.preventDefault();void jobAction('code');}}><label htmlFor="claude-callback-code">备用：网页显示的临时授权码</label><input id="claude-callback-code" data-testid="claude-callback-code" type="password" autoComplete="off" value={code} onChange={e=>setCode(e.target.value)} placeholder="不是 API Key；仅交给远端官方 CLI"/><button className="button secondary" type="submit" disabled={busy||!code.trim()}>提交授权码</button></form>}{job.error&&<p className="inline-error">{job.error}</p>}</div>}
 {error&&<p className="inline-error" role="alert">{error}</p>}
 {closeBrowser&&<Modal title="关闭远端浏览器" dismissible={!busy} onClose={()=>setCloseBrowser(false)}><p>关闭远端浏览器？未保存的网页输入会丢失。</p><p className="inline-note">登录状态和用户配置保留。</p>{error&&<p className="inline-error">{error}</p>}<div className="modal-actions"><button className="button secondary" disabled={busy} onClick={()=>setCloseBrowser(false)}>取消</button><button className="button primary" disabled={busy} onClick={()=>void control('stop')}>{busy?'正在关闭…':'确认关闭'}</button></div></Modal>}
 {setup&&<Modal title="配置远端浏览器" dismissible={!busy} onClose={()=>setSetup(undefined)}><p>{setup.installChrome?`Google Chrome 稳定版 ${setup.chromeVersion}`:'复用已有 Google Chrome'} · 不安装整套桌面环境</p><p className="inline-note">下方是远端包管理器的完整预演结果。仅允许新增必要依赖，不升级、替换或移除已有系统包。</p><ul>{setup.archives.map(a=><li key={a.name}>{a.name} · {a.license}</li>)}</ul><pre className="browser-setup-transaction">{setup.packageTransaction}</pre>{error&&<p className="inline-error">{error}</p>}<div className="modal-actions"><button className="button secondary" disabled={busy} onClick={()=>setSetup(undefined)}>取消</button><button className="button primary" disabled={busy} onClick={()=>void run(async()=>{const plan=setup;setSetup(undefined);await api('remote-browser/setup-apply',{id:host.id,planId:plan.id,confirm:true});const v=await api<RemoteBrowserState>('remote-browser/profiles',{id:host.id});if(live.current){setValue(v);notify('远端浏览器环境已核实。');}})}>{busy?'正在配置…':'确认安装所列组件'}</button></div></Modal>}
 {edit&&<Modal title={edit.key?'浏览器用户改名':'新增浏览器用户'} onClose={()=>setEdit(undefined)} dismissible={!busy}><label className="field"><span>用户名称</span><input data-autofocus maxLength={40} value={edit.label} onChange={e=>setEdit({...edit,label:e.target.value})} placeholder="例如：个人账号、工作账号"/></label><p className="inline-note">名称用于选择用户，不会合并或复制其他用户的登录数据。</p><div className="modal-actions"><button className="button secondary" disabled={busy} onClick={()=>setEdit(undefined)}>取消</button><button className="button primary" disabled={busy||!edit.label.trim()} onClick={()=>void mutate(edit.key?'rename':'create')}>保存</button></div></Modal>}
 {remove&&<Modal title="删除浏览器用户" onClose={()=>setRemove(undefined)} dismissible={!busy}><p>删除「{remove.label}」及这个浏览器用户的登录数据、Cookie 和浏览记录？其他用户保留。</p><p className="inline-note">这不会删除已经完成授权的 Claude CLI 账号。若要退出该账号，请在共享账号中移除。</p><div className="modal-actions"><button className="button secondary" disabled={busy} onClick={()=>setRemove(undefined)}>取消</button><button className="button primary" disabled={busy} onClick={()=>void mutate('delete')}>确认删除此用户</button></div></Modal>}
 </section>;
}
