import {useRef,useState} from 'react';
import type {SshHost} from '../../../packages/contracts';
import type {StudioSnapshot} from '../../../packages/workspace-control/types';
import {api} from './App';
import {Field,Modal,errorText,Icon} from './ui';
import WorkspaceExportDuration from './WorkspaceExportDuration';
import {ConnectionAddress} from './ConnectionAddress';

export default function WorkspaceExport({hosts,selectedId,notify}:{hosts:SshHost[];selectedId:string;notify:(message:string)=>void}){
 const [open,setOpen]=useState(false),[adminId,setAdminId]=useState(''),[memberId,setMemberId]=useState(''),[snapshot,setSnapshot]=useState<StudioSnapshot|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [ttlSeconds,setTtlSeconds]=useState(3600);
 const epoch=useRef(0),admins=hosts.filter(host=>host.role==='admin'),admin=admins.find(host=>host.id===adminId);
 const choose=async(id:string)=>{const request=++epoch.current;setAdminId(id);setSnapshot(null);setMemberId('');setError('');if(!id)return;setBusy(true);try{const next=await api<StudioSnapshot>('studio/list',{id});if(request!==epoch.current)return;if(next.availability!=='ready')throw Error(next.reason??'暂时无法读取工作空间。');setSnapshot(next);setMemberId(next.workspaces.find(space=>space.status==='active')?.id??'');}catch(error){if(request===epoch.current)setError(errorText(error));}finally{if(request===epoch.current)setBusy(false);}};
 const start=()=>{setTtlSeconds(3600);setOpen(true);const selected=hosts.find(host=>host.id===selectedId);const preferred=admins.find(host=>host.id===selectedId)??admins.find(host=>host.hostname===selected?.hostname&&host.port===selected.port&&host.ownerId===selected.ownerId)??admins[0];void choose(preferred?.id??'');};
 const save=async()=>{if(!admin||!memberId||busy)return;setBusy(true);setError('');try{const value=await api<{saved:boolean;path?:string}>('studio/export-managed',{id:admin.id,workspaceId:memberId,ttlSeconds});if(value.saved){setOpen(false);notify('工作空间文件已导出：'+value.path);}}catch(error){setError(errorText(error));}finally{setBusy(false);}};
 return <><button className="button secondary compact-button" data-testid="workspace-export-open" onClick={start}><Icon name="export" size={15}/>导出工作空间</button>{open&&<Modal title="导出工作空间" subtitle="一份文件，连接一台设备。" dismissible={!busy} onClose={()=>{epoch.current++;setOpen(false);}}>{admins.length>1&&<Field label="管理员连接"><select value={adminId} disabled={busy} onChange={event=>void choose(event.target.value)}>{admins.map(host=><option key={host.id} value={host.id}>{host.name}</option>)}</select></Field>}{admin&&<ConnectionAddress hostname={admin.hostname} port={admin.port}/>}<Field label="成员工作空间"><select data-testid="workspace-export-member" value={memberId} disabled={busy} onChange={event=>setMemberId(event.target.value)}>{!memberId&&<option value="">{busy?'正在读取…':'暂无可导出的空间'}</option>}{snapshot?.workspaces.filter(space=>space.status==='active').map(space=><option key={space.id} value={space.id}>{space.name}</option>)}</select></Field><WorkspaceExportDuration value={ttlSeconds} onChange={setTtlSeconds} disabled={busy}/><p className="inline-note">文件不包含已有设备或管理员的私钥。</p>{!admins.length&&<p className="inline-note">请先添加管理员连接。</p>}{error&&<p className="inline-error" role="alert">{error}</p>}<div className="modal-actions"><button className="button secondary" disabled={busy} onClick={()=>setOpen(false)}>取消</button><button className="button primary" data-testid="workspace-export-save" disabled={busy||!memberId} onClick={()=>void save()}>{busy?'正在处理…':'导出文件'}</button></div></Modal>}</>;
}
