import { _electron as electron } from 'playwright';
import electronPath from 'electron';
import { mkdir, mkdtemp, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
const root=path.resolve(fileURLToPath(new URL('..',import.meta.url)));
const output=path.join(root,'build/qa/ui-redo');await mkdir(output,{recursive:true});
const dataDir=await mkdtemp(path.join(os.tmpdir(),'awb-ui-redo-'));
const app=await electron.launch({executablePath:electronPath,args:[root],cwd:root,env:{...process.env,AGENT_WORKBENCH_TEST_DATA:dataDir,ELECTRON_RUN_AS_NODE:undefined}});
const checks=[],errors=[];const record=name=>{checks.push(name);console.log('PASS '+name);};
try {
 const page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(10000);
 await page.waitForFunction(()=>!!window.workbench);
 const call=(method,payload={})=>page.evaluate(({method,payload})=>window.workbench.call(method,payload),{method,payload});
 await call('theme/set',{theme:'dark'});
 const project=await call('project/create',{name:'AgentWorkbench',paths:[root,path.join(root,'docs')]});
 await call('project/create',{name:'参考资料',paths:[dataDir]});
 await page.getByTestId('new-session').click();
 await page.getByTestId('auto-submit-toggle').waitFor();
 assert.equal(await page.getByTestId('auto-submit-toggle').isChecked(),false);
 const placement=await page.evaluate(()=>{const p=document.querySelector('[data-testid="composer-project"]').getBoundingClientRect(),c=document.querySelector('.composer').getBoundingClientRect(),t=document.querySelector('[data-testid="auto-submit-toggle"]').getBoundingClientRect();return {p:p.toJSON(),c:c.toJSON(),t:t.toJSON(),onlySwitch:document.querySelector('.composer-options').textContent};});
 assert.ok(placement.p.top>placement.c.top-55&&placement.p.bottom<=placement.c.top+1);
 assert.ok(placement.t.top>=placement.c.bottom&&placement.t.bottom<await page.evaluate(()=>innerHeight));
 assert.equal(placement.onlySwitch.trim(),'翻译后直接发送');
 assert.equal((await call('state/get')).sessions.length,0);
 record('new task keeps project above composer and the direct-send translation switch visible below');
 await page.screenshot({path:path.join(output,'new-dark.png')});
 await page.getByTestId('composer-input').fill('保留这段尚未发送的草稿');
 await page.getByTestId('composer-project').click();await page.getByTestId('project-search').fill('Agent');
 await page.screenshot({path:path.join(output,'project-dark.png')});
 assert.equal(await page.locator('[data-testid^="project-folder-"]').count(),0);assert.equal(await page.getByTestId('project-picker-browse').count(),0);
 await page.getByTestId(`project-option-${project.id}`).click();
 assert.equal((await page.getByTestId('composer-project').innerText()).trim(),'AgentWorkbench');
 assert.equal(await page.getByTestId('composer-input').inputValue(),'保留这段尚未发送的草稿');
 await page.getByTestId('composer-runtime').click();await page.screenshot({path:path.join(output,'runtime-dark.png')});
 await page.getByRole('menuitemradio',{name:'Claude Claude Code 原生运行时'}).click();
 assert.equal(await page.getByTestId('composer-input').inputValue(),'保留这段尚未发送的草稿');
 await page.getByTestId('composer-runtime').press('ArrowDown');await page.keyboard.press('End');await page.keyboard.press('Enter');
 assert.match(await page.getByTestId('composer-runtime').innerText(),/离线示例/);
 assert.equal((await call('state/get')).sessions.length,0);
 record('project-only selection uses the primary folder and keyboard runtime switching preserves the lazy draft');
 await page.getByTestId('composer-permission').click();await page.screenshot({path:path.join(output,'permission-dark.png')});await page.keyboard.press('Escape');
 await page.getByTestId('auto-submit-toggle').click();assert.equal((await call('state/get')).autoSubmitTranslated,true);
 await page.getByTestId('auto-submit-toggle').click();assert.equal((await call('state/get')).autoSubmitTranslated,false);
 await page.getByTestId('load-demo').click();await page.getByTestId('prepare-draft').click();await page.getByTestId('submit-draft').waitFor();
 assert.equal((await call('state/get')).sessions[0].projectPath,root);
 await page.getByTestId('submit-draft').click();await page.getByText('This is an offline workflow demonstration.',{exact:false}).waitFor();
 assert.equal(await page.getByTestId('composer-project').count(),0);
 assert.equal(await page.getByTestId('composer-runtime').evaluate(el=>!!el.closest('.workspace-header')),true);
 assert.equal(await page.getByTestId('auto-submit-toggle').isVisible(),true);
 await page.screenshot({path:path.join(output,'conversation-dark.png')});
 record('first submission fixes project binding and moves identity controls to the conversation header');
 await page.getByTestId('composer-input').fill('文件打开时，这段草稿仍然可以继续编辑');
 await page.getByTestId('open-files').click();await page.getByTestId('file-dock').waitFor();
 await page.getByRole('textbox',{name:'文件路径',exact:true}).fill(path.join(root,'apps/desktop/renderer/FileBrowser.tsx'));
 await page.getByRole('button',{name:'前往路径'}).click();await page.getByTestId('code-preview').waitFor();await page.locator('.code-editor .view-lines').waitFor();
 assert.equal(await page.getByRole('dialog').count(),0);
 const dock=await page.getByTestId('file-dock').boundingBox(),composer=await page.locator('.composer').boundingBox();
 assert.ok(dock.x>=composer.x+composer.width);
 assert.equal(Math.round(dock.y),Math.round((await page.locator('.split-workspace').boundingBox()).y));
 await page.getByTestId('composer-input').fill('文件预览保持打开，对话仍然可编辑');
 await page.screenshot({path:path.join(output,'file-dock-dark.png')});
 const widthBefore=(await page.getByTestId('file-dock').boundingBox()).width;
 await page.getByRole('separator',{name:'调整文件面板宽度'}).press('ArrowLeft');
 assert.ok((await page.getByTestId('file-dock').boundingBox()).width>widthBefore);
 await page.getByRole('button',{name:'关闭文件面板'}).click();
 assert.equal(await page.getByTestId('composer-input').inputValue(),'文件预览保持打开，对话仍然可编辑');
 assert.equal(await page.getByTestId('translation-chinese').isVisible(),true);
 record('file preview docks beside an editable conversation, resizes, and restores the bilingual layout on close');
 await call('theme/set',{theme:'light'});await page.screenshot({path:path.join(output,'conversation-light.png')});
 await page.getByTestId('new-session').click();await page.screenshot({path:path.join(output,'new-light.png')});
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setContentSize(860,640));await page.waitForFunction(()=>innerWidth===860);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.getByTestId('composer-project').click();
 const bounds=await page.getByTestId('project-picker').boundingBox();assert.ok(bounds.y>=0&&bounds.y+bounds.height<=640);
 await page.screenshot({path:path.join(output,'narrow-light.png')});await page.keyboard.press('Escape');
 assert.equal(await page.getByTestId('auto-submit-toggle').isVisible(),true);
 await page.getByTestId('open-files').click();await page.getByTestId('file-dock').waitFor();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 const narrowDock=await page.getByTestId('file-dock').boundingBox(),narrowComposer=await page.locator('.composer').boundingBox();
 assert.ok(narrowDock.x>=narrowComposer.x+narrowComposer.width);
 assert.equal(await page.getByTestId('composer-input').isVisible(),true);
 await page.screenshot({path:path.join(output,'file-dock-narrow.png')});
 await page.getByRole('button',{name:'关闭文件面板'}).click();
 record('both themes and 860px window retain the project popup and visible translation switch');
 if(!await page.getByTestId('auto-submit-toggle').isChecked())await page.getByTestId('auto-submit-toggle').click();await page.waitForFunction(()=>document.querySelector('[data-testid="auto-submit-toggle"]').checked);await page.getByTestId('composer-input').fill('翻译服务尚未配置时保留原稿');await page.getByTestId('prepare-draft').click();await page.getByTestId('prepare-original').waitFor();
 const messagesBeforeFallback=(await call('state/get')).sessions.map(({id,messages})=>({id,messages}));
 await page.getByTestId('prepare-original').click();await page.getByTestId('draft-preview').waitFor();
 assert.equal((await page.getByTestId('draft-submission-preview').innerText()).trim(),'翻译服务尚未配置时保留原稿');
 assert.deepEqual((await call('state/get')).sessions.map(({id,messages})=>({id,messages})),messagesBeforeFallback);await page.keyboard.press('Escape');
 assert.equal(await page.getByTestId('composer-input').inputValue(),'翻译服务尚未配置时保留原稿');record('translation failure retains an explicit original-text preview and never submits it automatically');
 assert.deepEqual(errors,[]);
 await writeFile(path.join(output,'report.json'),JSON.stringify({passed:true,checks,errors,dataDir,evidence:'Isolated Electron, actual rendered UI and offline demonstration. No model, SSH or translation-provider requests.'},null,2));
} finally { await app.close(); }
