import { openWorkbenchSettings, navigateWorkbench } from './ui-control-helpers.mjs';
import { _electron as electron } from 'playwright';
import electronPath from 'electron';
import { mkdir,readFile,writeFile } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { setTimeout as pause } from 'node:timers/promises';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const appRoot=path.resolve(process.env.AGENT_WORKBENCH_TEST_APP??root);
const output=path.join(root,'build/qa');await mkdir(output,{recursive:true});
const dataDir=path.join(output,`synthetic-state-${Date.now()}`);await mkdir(dataDir,{recursive:true});
const env={...process.env,AGENT_WORKBENCH_TEST_DATA:dataDir,AGENT_WORKBENCH_TEST_CLAUDE_EXECUTABLE:process.env.AGENT_WORKBENCH_TEST_CLAUDE_EXECUTABLE??path.join(os.homedir(),'.local/bin/claude.exe'),AGENT_WORKBENCH_TEST_CODEX_EXECUTABLE:process.env.AGENT_WORKBENCH_TEST_CODEX_EXECUTABLE??path.join(os.homedir(),'AppData/Roaming/npm/node_modules/@openai/codex/node_modules/@openai/codex-win32-x64/vendor/x86_64-pc-windows-msvc/bin/codex.exe')};delete env.ELECTRON_RUN_AS_NODE;
const screenshots=!process.argv.includes('--no-screenshots');
const checks=[];const errors=[];let app;
const record=(name)=>{checks.push({name,passed:true});console.log(`PASS ${name}`);};
const waitUntil=async(predicate,description='condition')=>{const end=Date.now()+15000;while(Date.now()<end){if(await predicate())return;await pause(25);}throw new Error(`Timed out waiting for ${description}`);};
try{
 app=await electron.launch({executablePath:electronPath,args:[appRoot],cwd:root,env,timeout:45000});
 const page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));
 await page.waitForFunction(()=>!!window.workbench,{timeout:20000});
 const prefs=await app.evaluate(({BrowserWindow})=>{const p=BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences();return {contextIsolation:p.contextIsolation,sandbox:p.sandbox,nodeIntegration:p.nodeIntegration};});
 assert.deepEqual(prefs,{contextIsolation:true,sandbox:true,nodeIntegration:false});record('actual Electron renderer security flags');
 assert.equal(await page.evaluate(()=>typeof window.require),'undefined');record('renderer has no Node require');
 const chooseMenu=async(id,value)=>{await page.getByTestId(id).click();await page.locator(`[role=menuitemradio][data-value="${value}"]`).click();};
 const call=(method,payload={})=>page.evaluate(async({method,payload})=>window.workbench.call(method,payload),{method,payload});
 const focused=async(testId)=>page.evaluate(id=>document.activeElement?.getAttribute('data-testid')===id,testId);
 const loadDemo=async()=>{if(!await page.getByTestId('load-demo').count())await page.getByTestId('composer-runtime').click();await page.getByTestId('load-demo').click();const sample=await call('demo.sample/get');await waitUntil(async()=>await page.getByTestId('composer-input').inputValue()===sample.input,'demo sample loaded before submission');};
 const toggleAuto=async()=>{await page.getByTestId('auto-submit-toggle').click();};
 const choosePermission=async(mode)=>{await page.getByTestId('composer-permission').click();await page.getByTestId(`permission-option-${mode}`).click();await page.getByTestId('permission-menu').waitFor({state:'hidden'});};
 const checkPermission=async(mode,modes)=>{
  await page.getByTestId('composer-permission').click();await page.getByTestId('permission-menu').waitFor();
  assert.equal(await page.getByTestId(`permission-option-${mode}`).getAttribute('aria-checked'),'true');
  if(modes)assert.deepEqual(await page.getByTestId('permission-menu').getByRole('menuitemradio').evaluateAll(items=>items.map(item=>item.getAttribute('data-testid').replace('permission-option-','')).sort()),[...modes].sort());
  await page.keyboard.press('Escape');await page.getByTestId('permission-menu').waitFor({state:'hidden'});
 };
 const checkPermissionPosition=async(context)=>{
  await page.getByTestId('composer-permission').waitFor({state:'visible'});
  const position=await page.evaluate(()=>{
   const permission=document.querySelector('[data-testid="composer-permission"]');const input=document.querySelector('[data-testid="composer-input"]');const send=document.querySelector('[data-testid="prepare-draft"]');const composer=input?.closest('.composer');const toolbar=permission?.closest('.composer-toolbar');
   const bounds=element=>{if(!element)return null;const {left,right,top,bottom,width,height}=element.getBoundingClientRect();return {left,right,top,bottom,width,height};};
   return {insideToolbar:!!toolbar&&toolbar.closest('.composer')===composer,permission:bounds(permission),input:bounds(input),send:bounds(send),composer:bounds(composer),viewport:{width:innerWidth,height:innerHeight}};
  });
  const {permission,input,send,composer,viewport}=position;const detail=`${context}: ${JSON.stringify(position)}`;
  assert.ok(position.insideToolbar,detail);assert.ok(permission&&input&&send&&composer,detail);assert.ok(permission.width>0&&permission.height>0,detail);
  assert.ok(permission.left>=composer.left&&permission.right<=composer.right&&permission.top>=input.bottom-1&&permission.bottom<=composer.bottom,detail);
  assert.ok((permission.left+permission.right)/2<(composer.left+composer.right)/2,detail);assert.ok(permission.right<=send.left&&(send.left+send.right)/2>(composer.left+composer.right)/2,detail);
  assert.ok(permission.top<send.bottom&&permission.bottom>send.top&&permission.bottom<=viewport.height&&permission.left>=0&&permission.right<=viewport.width,detail);
  record(`${context}: permission stays inside the lower-left composer toolbar, opposite Send`);
 };
 const checkNarrowPermissionPosition=async(context)=>{
  const original=await app.evaluate(({BrowserWindow})=>{const window=BrowserWindow.getAllWindows()[0];return {bounds:window.getBounds(),content:window.getContentSize()};});
  let switchedPane=false;
  try{
   await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setContentSize(860,640));await page.waitForFunction(()=>innerWidth===860&&innerHeight===640&&document.querySelector('[data-testid="bilingual-result"]')?.classList.contains('compact-split'));
   if(await page.getByTestId('toggle-translation-pane').count() && await page.getByTestId('toggle-translation-pane').getAttribute('aria-pressed')==='true'){await page.getByTestId('toggle-translation-pane').click();switchedPane=true;}
   await checkPermissionPosition(`${context} at 860x640`);
  }finally{
   await app.evaluate(({BrowserWindow},bounds)=>BrowserWindow.getAllWindows()[0].setBounds(bounds),original.bounds);await page.waitForFunction(([width,height])=>innerWidth===width&&innerHeight===height,original.content);
   if(switchedPane)await page.getByTestId('toggle-translation-pane').click();
  }
 };
 await page.getByTestId('new-session').click();
 await page.getByTestId('composer-input').waitFor();
 assert.equal(await page.getByRole('dialog').count(),0);assert.equal((await call('state/get')).sessions.length,0);assert.equal((await call('state/get')).projects.length,0);assert.equal(await page.getByTestId('composer-project').count(),1);assert.equal(await page.getByTestId('composer-project-path').count(),0);assert.equal(await page.getByTestId('session-skills').count(),0);record('New conversation opens an inline projectless composer without creating an empty thread');
 await page.getByTestId('new-session').click();assert.equal((await call('state/get')).sessions.length,0);await chooseMenu('composer-runtime','demo');if(screenshots)await page.screenshot({path:path.join(output,'new-conversation.png'),fullPage:true});record('runtime and optional project choices live beside the composer');
 await checkPermissionPosition('New conversation');await checkNarrowPermissionPosition('New conversation');
 assert.equal(await page.locator('.composer-footnote,.composer-context').count(),0);assert.equal(await page.locator('.composer-options [role=switch]').count(),1);assert.equal(await page.getByTestId('composer-runtime').evaluate(el=>!!el.closest('.new-session-context')),true);record('new task context is above the composer and the translation switch is directly below');
 await page.getByTestId('composer-permission').press('ArrowDown');await page.getByTestId('permission-menu').waitFor();await waitUntil(()=>focused('permission-option-default'),'initial permission focus');await page.keyboard.press('End');assert.equal(await focused('permission-option-full-access'),true);await page.keyboard.press('Home');assert.equal(await focused('permission-option-default'),true);await page.keyboard.press('ArrowDown');assert.equal(await focused('permission-option-read-only'),true);await page.keyboard.press('Escape');await page.getByTestId('permission-menu').waitFor({state:'hidden'});assert.equal(await focused('composer-permission'),true);
 await page.getByTestId('composer-permission').press('ArrowDown');await page.getByTestId('permission-menu').waitFor();await page.keyboard.press('Tab');await page.getByTestId('permission-menu').waitFor({state:'hidden'});assert.equal(await focused('composer-permission'),false);record('permission menu supports arrow, Home, End, Escape and Tab navigation with focus restoration');
 const draftSentinel='Draft survives runtime, permission and project choices';await page.getByTestId('composer-input').fill(draftSentinel);
 await checkPermission('default',['default','read-only','full-access']);assert.equal(await focused('composer-permission'),true);await choosePermission('full-access');await checkPermission('full-access');
 await chooseMenu('composer-runtime','claude');await checkPermission('default',['default','accept-edits','plan','full-access']);await choosePermission('plan');await checkPermission('plan');await choosePermission('accept-edits');await checkPermission('accept-edits');
 await chooseMenu('composer-runtime','codex');await checkPermission('default',['default','read-only','full-access']);await choosePermission('read-only');await checkPermission('read-only');
 await chooseMenu('composer-runtime','demo');await checkPermission('default',['default','read-only','full-access']);await choosePermission('read-only');
 await page.getByTestId('composer-permission').click();await page.getByTestId('permission-menu').waitFor();await page.getByTestId('composer-input').click();await page.getByTestId('permission-menu').waitFor({state:'hidden'});assert.equal(await focused('composer-input'),true);assert.equal(await page.getByTestId('composer-input').inputValue(),draftSentinel);assert.equal((await call('state/get')).sessions.length,0);record('runtime-specific permission choices reset safely on runtime changes and preserve the unsent draft without creating sessions');
 const sample=await call('demo.sample/get');
 const load=page.getByTestId('load-demo');
 if(await load.count())await load.click();else await page.getByTestId('composer-input').fill(sample.input);
 await page.getByTestId('composer-input').waitFor();await waitUntil(async()=>await page.getByTestId('composer-input').inputValue()===sample.input,'loaded demo sample');assert.equal(await page.getByTestId('composer-input').inputValue(),sample.input);record('sample loads into the actual composer');
 assert.equal((await call('state/get')).autoSubmitTranslated,false);
 await page.getByTestId('composer-input').evaluate(input=>{input.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',bubbles:true}));input.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',bubbles:true}));});
 await page.getByTestId('submit-draft').waitFor({timeout:10000});
 const session=(await call('state/get')).sessions[0];assert.equal(session.projectId,null);assert.equal(session.permissionMode,'read-only');assert.equal((await call('state/get')).sessions.length,1);assert.equal(session.messages.length,0);record('rapid Enter lazily creates exactly one unassigned session with its selected permission and preserves the draft');
 await page.getByRole('dialog').waitFor();record('Enter opens a modal preview with direct send off by default');
 assert.equal(await page.getByTestId('draft-preview').locator('textarea,input').count(),0);assert.equal(await page.getByTestId('submit-draft').isEnabled(),true);const reviewBounds=await page.getByRole('dialog').boundingBox(),sourceBounds=await page.getByTestId('draft-chinese-preview').boundingBox(),sentBounds=await page.getByTestId('draft-submission-preview').boundingBox();assert.ok(reviewBounds.width<=620&&sourceBounds.y+sourceBounds.height<=sentBounds.y,'compact preview stacks the original above the submitted text');record('compact preview shows Chinese above English without an inline editor');
 if(screenshots)await page.screenshot({path:path.join(output,'preview-modal.png'),fullPage:true});
 await page.getByTestId('draft-edit').click();assert.equal(await page.getByTestId('composer-input').inputValue(),sample.input);await waitUntil(()=>focused('composer-input'),'composer focus after returning from preview');assert.equal(await page.getByTestId('submit-draft').count(),0);record('returning from preview retains the original draft, restores composer focus and invalidates old confirmation');
 await page.getByTestId('composer-input').fill('First line');await page.getByTestId('composer-input').press('Shift+Enter');assert.ok((await page.getByTestId('composer-input').inputValue()).includes('\n'));assert.equal(await page.getByRole('dialog').count(),0);record('Shift Enter adds a newline instead of sending');
 await loadDemo();await page.getByTestId('composer-input').press('Enter');await page.getByTestId('submit-draft').waitFor();
 let state=await call('state/get');assert.equal(state.sessions[0].messages.length,0);record('preview does not dispatch a turn');
 await page.getByTestId('submit-draft').click();
 await waitUntil(async()=>{const s=await call('state/get');return s.sessions[0]?.messages.length===2;},'completed demo turn');
 state=await call('state/get');const messages=state.sessions[0].messages;
 await page.getByTestId('unassigned-sessions').locator(`[data-session-id="${session.id}"]`).waitFor();record('projectless history is visible in the sidebar');
 assert.equal(messages[0].original,sample.input);assert.equal(messages[0].submitted,sample.translated);assert.equal(messages[1].translationStatus,'complete');
 await page.getByTestId(`user-source-${messages[0].id}`).waitFor();assert.ok((await page.getByTestId(`user-source-${messages[0].id}`).innerText()).includes(sample.translated.replaceAll('`','')));assert.ok((await page.getByTestId(`user-chinese-${messages[0].id}`).innerText()).includes(sample.input.replaceAll('`','')));record('user message also displays exact submitted text left and local Chinese right');
 await page.getByText('This is an offline workflow demonstration.',{exact:false}).first().waitFor();
 await page.getByText('这是一次离线工作流演示。',{exact:false}).first().waitFor();record('reviewed input and bilingual final display through IPC');
 await checkPermission('read-only');await choosePermission('full-access');await waitUntil(async()=>(await call('state/get')).sessions.find(item=>item.id===session.id)?.permissionMode==='full-access','saved session permission');await checkPermission('full-access');assert.equal((await call('state/get')).sessions[0].messages.length,2);record('an idle historical session can change and persist permission without replacing its messages');
 await checkPermissionPosition('Historical conversation');await checkNarrowPermissionPosition('Historical conversation');
 if(screenshots)await page.screenshot({path:path.join(output,'light-workspace.png'),fullPage:true});
 await call('theme/set',{theme:'dark'});await page.waitForTimeout(150);
 if(screenshots)await page.screenshot({path:path.join(output,'dark-workspace.png'),fullPage:true});record(screenshots?'light and dark desktop screenshots':'light and dark themes switch without screenshot capture');
 const before=messages[1].original;await call('message/retranslate',{sessionId:session.id,messageId:messages[1].id});state=await call('state/get');assert.equal(state.sessions[0].messages.length,2);assert.equal(state.sessions[0].messages[1].original,before);record('retry only translates, never reruns the agent');
 const sourceBlock=page.getByTestId(`source-block-${messages[1].id}-1`);const translatedBlock=page.getByTestId(`translation-block-${messages[1].id}-1`);
 await sourceBlock.hover();await page.waitForFunction(id=>[...document.querySelectorAll(`[data-sync-key="${id}:1"]`)].every(element=>element.classList.contains('is-matched')),messages[1].id);record('hover highlights the matching source and translation blocks');
 const separator=page.getByTestId('split-separator');const widthBefore=Number(await separator.getAttribute('aria-valuenow'));await separator.focus();await separator.press('ArrowRight');assert.ok(Number(await separator.getAttribute('aria-valuenow'))>widthBefore);await separator.press('Home');
 const grip=await separator.boundingBox();assert.ok(grip);await page.mouse.move(grip.x+grip.width/2,grip.y+grip.height/2);await page.mouse.down();await page.mouse.move(grip.x+75,grip.y+grip.height/2,{steps:5});await page.mouse.up();assert.ok(Number(await separator.getAttribute('aria-valuenow'))>widthBefore);await separator.press('Home');record('split divider resizes by pointer and keyboard');
 for(let i=0;i<2;i++){await loadDemo();await page.getByTestId('prepare-draft').click();await page.getByTestId('submit-draft').click();await waitUntil(async()=>{const current=await call('state/get');return current.sessions[0].messages.filter(message=>message.role==='assistant').length===i+2;},'next completed demo turn');}
 const priorScroll=await page.getByTestId('translation-pane').evaluate(element=>{element.scrollTop=element.scrollHeight;return element.scrollTop;});assert.ok(priorScroll>0);
 await sourceBlock.click();await page.waitForFunction(previous=>document.querySelector('[data-testid="translation-pane"]').scrollTop<previous,priorScroll);record('clicking a text block tracks its counterpart in the opposite pane');
 assert.equal(await page.getByTestId('sync-scroll-toggle').count(),0);record('no forced-scroll checkbox remains');
 await page.locator(`[data-session-id="${session.id}"]`).click({button:'right'});await page.getByTestId('session-copy-submenu').click();await page.getByRole('menuitem',{name:'复制深度链接',exact:true}).waitFor();if(screenshots)await page.screenshot({path:path.join(output,'context-menu.png'),fullPage:true});await page.keyboard.press('Escape');await page.keyboard.press('Escape');record('real right-click menu exposes deep-link action');
 await toggleAuto();await waitUntil(async()=>(await call('state/get')).autoSubmitTranslated===true,'direct send enabled');assert.equal((await call('state/get')).autoSubmitTranslated,true);await loadDemo();await page.getByTestId('composer-input').press('Enter');await page.getByTestId('session-stop').waitFor();assert.equal(await page.getByTestId('composer-permission').isEnabled(),true);await page.getByTestId('session-stop').click();record('permission selection remains available during the running offline turn');
 await waitUntil(async()=>{const current=await call('state/get');return current.sessions[0].status==='idle'&&current.sessions[0].messages.length===8;},'stopped demo turn');assert.equal(await page.getByRole('dialog').count(),0);assert.match((await call('state/get')).sessions[0].messages.at(-1).original,/stopped/);record('direct-send bypasses preview only when enabled and Stop cancels the demo turn');
 await toggleAuto();await waitUntil(async()=>(await call('state/get')).autoSubmitTranslated===false,'direct send disabled');assert.equal((await call('state/get')).autoSubmitTranslated,false);
 await page.getByTestId(`edit-message-${messages[0].id}`).click();assert.equal(await page.getByTestId('composer-input').inputValue(),sample.input);assert.equal((await call('state/get')).sessions[0].messages.length,8);record('edit and resend restores the Chinese request without deleting previous history');
 await assert.rejects(call('exec',{command:'should never execute'}));record('unknown IPC is rejected');
 await assert.rejects(call('draft/prepare',{sessionId:session.id,text:'普通中文应当在没有翻译服务时阻止发送'}));state=await call('state/get');assert.equal(state.sessions[0].messages.length,8);record('missing provider cannot silently send Chinese');
 await call('session/update',{id:session.id,title:'QA · 双语确认',pinned:true});
 await openWorkbenchSettings(page);{if(screenshots)await page.screenshot({path:path.join(output,'settings.png'),fullPage:true});record('settings screen renders');}
 await page.getByTestId('translation-endpoint').fill('https://translation.example.test/v1');await page.getByTestId('translation-model').fill('synthetic-model');await page.getByTestId('translation-key').fill('ONLY-LOCAL-QA-NOT-A-REAL-CREDENTIAL');await page.getByTestId('translation-consent').check();await page.getByTestId('save-translation').click();
 await waitUntil(async()=>{const s=await call('state/get');return s.translation.hasKey&&s.translation.baseUrl==='https://translation.example.test/v1';},'saved synthetic key');await page.waitForFunction(()=>document.querySelector('[data-testid="translation-key"]').value==='');assert.equal(await page.getByTestId('translation-key').inputValue(),'');
 assert.ok(!(await readFile(path.join(dataDir,'state.json'),'utf8')).includes('ONLY-LOCAL-QA'));assert.ok(!(await readFile(path.join(dataDir,'secrets/translation-key.bin'))).includes(Buffer.from('ONLY-LOCAL-QA')));record('actual OS encryption stores a synthetic key without plaintext in renderer state or disk');
 await page.getByTestId('settings-memory').click();await page.getByTestId('native-memory-settings').waitFor();
 const nativeRoot=path.join(dataDir,'native-home','.codex','memories');await mkdir(nativeRoot,{recursive:true});await writeFile(path.join(nativeRoot,'memory_summary.md'),'Keep requested Chinese documentation in Chinese.');await call('native-memory/configure',{enabled:true,initialSources:'codex'});
 const context=await call('session/context',{sessionId:session.id});assert.ok(!context.items.some(item=>item.kind==='memory'));assert.ok((await call('native-memory/get')).pendingClaude>0);if(screenshots)await page.screenshot({path:path.join(output,'shared-memory.png'),fullPage:true});record('native memory is archived locally for a native-runtime handoff, not permanently injected');
 const importDirectory=path.join(dataDir,'native-home','.agents','skills','qa-global-skill');await mkdir(importDirectory,{recursive:true});const skillFile=path.join(importDirectory,'SKILL.md');const skillText='---\nname: qa-global-skill\ndescription: A global synthetic test skill.\n---\n# Full skill\nREAD_ONLY_BODY_SENTINEL\n';await writeFile(skillFile,skillText);
 await page.getByTestId('settings-skills').click();await page.getByTestId('skills-list').getByText('qa-global-skill',{exact:true}).waitFor();record('native skills are discovered directly from the isolated native home');
 const catalog=await call('native-skills/list');const imported=catalog.skills.find(item=>item.name==='qa-global-skill');assert.ok(imported);assert.equal(imported.body,undefined);assert.equal(imported.markdown,undefined);assert.equal(await page.getByTestId('shared-skill-markdown').count(),0);
 await page.getByTestId(`native-skill-${imported.id}`).locator('.shared-item-main').click();await page.getByTestId('shared-skill-markdown').waitFor();assert.ok((await page.getByTestId('shared-skill-markdown').innerText()).includes('READ_ONLY_BODY_SENTINEL'));record('native skill catalog omits bodies and opens only the chosen version-checked Markdown');
 await page.getByRole('dialog').getByLabel('关闭窗口',{exact:true}).click();
 await navigateWorkbench(page,'capabilities');await page.getByTestId('capability-list').waitFor();await page.locator('.capability-row').nth(8).waitFor();assert.ok(await page.locator('.capability-row').count()>8);record('native capability gates remain explicit in the assembled UI');
 const folderA=path.join(dataDir,'project-a');const folderB=path.join(dataDir,'project-b');await mkdir(folderA);await mkdir(folderB);const project=await call('project/create',{name:'QA Multi-folder',paths:[folderA,folderB]});
 await navigateWorkbench(page,'workspace');const current=await call('state/get');assert.equal(current.projects.find(p=>p.id===project.id).paths.length,2);await page.locator(`[data-project-id="${project.id}"] .project-heading`).click({button:'right'});await page.getByTestId('project-manage-folders').click();assert.equal(await page.locator('.managed-folder').count(),2);await page.keyboard.press('Escape');record('multi-folder project is visible in the actual manage-folders dialog');
 await page.getByTestId('new-session').click();await page.getByTestId('composer-input').fill('Draft survives runtime switch');await chooseMenu('composer-runtime','claude');assert.equal(await page.getByTestId('composer-input').inputValue(),'Draft survives runtime switch');await chooseMenu('composer-runtime','demo');assert.equal(await page.getByTestId('composer-project').count(),1);record('project control and runtime switching preserve the lazy draft');
 await page.locator(`[data-session-id="${session.id}"]`).click();await checkPermission('full-access');assert.equal((await call('state/get')).sessions.find(item=>item.id===session.id).messages.length,8);record('reopening history restores its saved permission and messages');
 await app.close();app=undefined;
 const disk=JSON.parse(await readFile(path.join(dataDir,'state.json'),'utf8'));assert.equal(disk.sessions[0].title,'QA · 双语确认');assert.equal(disk.sessions[0].permissionMode,'full-access');assert.equal(disk.theme,'dark');record('atomic state persisted including the selected session permission');
 app=await electron.launch({executablePath:electronPath,args:[appRoot,`agent-workbench://threads/${session.id}`],cwd:root,env,timeout:45000});const restarted=await app.firstWindow();restarted.on('pageerror',e=>errors.push(e.message));await restarted.waitForFunction(()=>!!window.workbench);
 const restored=await restarted.evaluate(()=>window.workbench.call('state/get'));assert.equal(restored.sessions[0].title,'QA · 双语确认');assert.equal(restored.sessions[0].messages[1].original,before);assert.equal(restored.sessions[0].permissionMode,'full-access');record('actual process restart preserves originals, identity and permission');
 await restarted.getByTestId('composer-input').waitFor();const navigation=await restarted.evaluate(()=>window.workbench.call('navigation/get'));assert.equal(navigation.sessionId,session.id);record('native deep-link launch opens the exact existing session without sending a turn');
 await restarted.getByTestId('composer-permission').click();await restarted.getByTestId('permission-menu').waitFor();assert.equal(await restarted.getByTestId('permission-option-full-access').getAttribute('aria-checked'),'true');await restarted.keyboard.press('Escape');record('restarted deep-linked history renders its saved permission selection');
 assert.deepEqual(errors,[]);record('no renderer exceptions');
 await writeFile(path.join(output,'desktop-report.json'),JSON.stringify({timestamp:new Date().toISOString(),electron:await app.evaluate(()=>process.versions.electron),dataDir,screenshots,checks,errors,scope:'Synthetic offline demo; no SSH or real model requests.'},null,2));
 console.log(`Desktop QA: ${checks.length} checks passed; ${output}`);
}finally{if(app)await app.close();}
