import {readFile,open} from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import type {SshHost} from '../contracts';
import {runSsh,validateSshHost,type SshRunner} from '../ssh-transport';
import {accountSetupScript} from './setup';
import type {FileView} from '../../apps/desktop/host/file-browser';

export interface RemoteFileView extends FileView {revision:string;modified?:number;mode?:string;link?:boolean}
export interface ResourcePolicy {revision:number;autoMemory:boolean}
export interface RemoteResources {
 observedAt:number; memory:{total:number;used:number;available:number;swapTotal:number;swapUsed:number};storage:{path:string;total:number;used:number;available:number};
 policy:ResourcePolicy;runtime:{available:boolean;sessions?:{sessionId:string;idle:boolean;closing:boolean;health:string}[];interrupted?:{sessionId:string;threadId?:string;turnId?:string}[];lastReclaim?:{closed:string[];protected:number;pending:number;observedAt:number}|null;probeSeconds?:number;unresponsiveSeconds?:number};
}
const labels:Record<string,string>={ADMIN_REQUIRED:'请从 SSH 管理员连接管理远端资源。',RESOURCE_POLICY_CHANGED:'设置已被另一个窗口修改，请刷新后重试。',RESOURCE_BROKER_UNAVAILABLE:'远端原生服务不可用或版本未更新；未回收任何进程。',RESOURCE_OPERATION_UNCONFIRMED:'远端操作未确认，请刷新核对；不会自动重试。',REMOTE_FILE_CHANGED:'文件已变化，请重新读取后再操作。',REMOTE_FILE_PERMISSION:'远端系统权限不足。',REMOTE_FILE_EXISTS:'目标已存在；未覆盖。',REMOTE_FILE_MISSING:'远端文件不存在，请刷新。',REMOTE_FILE_LINK:'链接目标已变化，请刷新后重试。',REMOTE_FILE_SPECIAL:'此操作需要普通文件或目录，设备文件需使用对应原生工具。',REMOTE_FILE_MOUNT:'不跨挂载点移动或递归删除。',REMOTE_FILE_COPY_REGULAR_ONLY:'此操作需要普通文件、目录或符号链接。',REMOTE_FILE_OPERATION_UNCONFIRMED:'文件操作未确认，可能已部分完成；请刷新核对。'};
const posix=(value:unknown):value is string=>typeof value==='string'&&value.startsWith('/')&&value.length<=4096&&!/[\x00-\x1f]/.test(value)&&!value.split('/').some(v=>v==='..'||v==='.');
const revision=(value:unknown)=>typeof value==='string'&&/^[a-f0-9]{64}$/.test(value);
export class RemoteResourceService {
 constructor(private runner:SshRunner=runSsh,private dialogs?:{upload():Promise<string|null>;download(name:string):Promise<string|null>}){}
 private async request(host:SshHost,request:unknown){validateSshHost(host);if(host.role!=='admin'||host.username!=='root')throw Error(labels.ADMIN_REQUIRED);const response=await this.runner(host,'exec python3 -B -',{stdin:accountSetupScript(request)});let result:any;try{result=JSON.parse(response.stdout);}catch{throw Error(labels.RESOURCE_OPERATION_UNCONFIRMED);}if(response.exitCode!==0||result?.ok!==true)throw Error(labels[result?.error]??labels.RESOURCE_OPERATION_UNCONFIRMED);return result.value;}
 async read(host:SshHost):Promise<RemoteResources>{const result=await this.request(host,{method:'resources/read'});if(!result||!Number.isFinite(result.observedAt)||!result.memory||!result.storage||Object.values(result.memory).some(n=>typeof n!=='number'||!Number.isFinite(n)||n<0)||['total','used','available'].some(k=>!Number.isFinite(result.storage[k])||result.storage[k]<0)||typeof result.runtime?.available!=='boolean')throw Error('远端资源回执无效。');this.policy(result.policy);return result;}
 private policy(value:any):ResourcePolicy{if(!value||!Number.isSafeInteger(value.revision)||value.revision<0||typeof value.autoMemory!=='boolean')throw Error('远端资源设置回执无效。');return {revision:value.revision,autoMemory:value.autoMemory};}
 async configure(host:SshHost,revision:number,autoMemory:boolean){if(!Number.isSafeInteger(revision)||typeof autoMemory!=='boolean')throw Error('无效的资源设置。');return this.policy(await this.request(host,{method:'resources/configure',revision,autoMemory}));}
 async reclaim(host:SshHost){const value=await this.request(host,{method:'resources/reclaim'});if(typeof value?.result?.available!=='boolean'||!Array.isArray(value.result.closed)||!Number.isSafeInteger(value.result.protected))throw Error('内存回收回执无效。');return value as {result:{available:boolean;closed:string[];protected:number;pending?:number}};}
 async browse(host:SshHost,target:string):Promise<RemoteFileView>{if(!posix(target))throw Error('请输入远端 POSIX 绝对路径。');const value=await this.request(host,{method:'remote-files/browse',path:target});if(!value||!posix(value.path)||!posix(value.parent)||!revision(value.revision)||!['directory','text','unsupported'].includes(value.kind)||value.kind==='text'&&typeof value.content!=='string'||value.kind==='directory'&&(!Array.isArray(value.entries)||value.entries.some((e:any)=>!posix(e.path)||typeof e.name!=='string'||typeof e.directory!=='boolean')))throw Error('远端文件回执无效。');return value;}
 async mutate(host:SshHost,operation:string,input:{path:string;revision?:string;destination?:string;content?:string;confirm?:boolean}){if(!['mkdir','write','move','copy','remove'].includes(operation)||!posix(input.path)||input.destination!==undefined&&!posix(input.destination)||input.revision!==undefined&&!revision(input.revision)||input.content!==undefined&&typeof input.content!=='string'||operation==='remove'&&input.confirm!==true)throw Error('无效的远端文件操作。');return this.request(host,{...input,method:'remote-files/'+operation});}
 async upload(host:SshHost,directory:string){if(!posix(directory)||!this.dialogs)throw Error('上传入口不可用。');const source=await this.dialogs.upload();if(!source)return {cancelled:true};const file=await open(source,'r');try{const meta=await file.stat();if(!meta.isFile())throw Error('请选择普通文件。');const data=await file.readFile();return await this.request(host,{method:'remote-files/upload',path:directory.replace(/\/$/,'')+'/'+path.basename(source),data:data.toString('base64')});}finally{await file.close();}}
 async download(host:SshHost,target:string,rev:string){if(!posix(target)||!revision(rev)||!this.dialogs)throw Error('下载入口不可用。');const output=await this.dialogs.download(path.posix.basename(target));if(!output)return {cancelled:true};const result=await this.request(host,{method:'remote-files/download',path:target,revision:rev});if(typeof result?.data!=='string')throw Error('下载回执无效。');const data=Buffer.from(result.data,'base64');if(data.length!==result.bytes||createHash('sha256').update(data).digest('hex')!==result.sha256)throw Error('下载校验失败，未保存。');const file=await open(output,'wx',0o600);try{await file.writeFile(data);await file.sync();}finally{await file.close();}const saved=await readFile(output);if(createHash('sha256').update(saved).digest('hex')!==result.sha256)throw Error('本机保存回读失败，请核对下载结果。');return {path:output,bytes:data.length};}
}
